"use client";
import { useState } from "react";
import Header from "../../Header";
import Footer from "../../Footer";

const categories = ["All", "FPS & Gaming", "RAM Optimization", "SSD & Disk Cleaning", "Windows Debloat", "GPU Drivers & Settings", "Network & Latency", "System Stability", "Utility Tools"];

const optimizationData = [
  { id: 1, title: "Enable Game Mode", category: "FPS & Gaming", type: "Setting", summary: "Prioritizes system resources specifically for active game processes.", whatItDoes: "Prevents background Windows Update drivers from installing and limits background apps during gameplay.", whenToUse: "Keep this permanently enabled on Windows 10 and 11.", steps: ["Press Win + I to open Settings.", "Navigate to Gaming → Game Mode.", "Toggle Game Mode to ON."], url: "" },
  { id: 2, title: "Enable Hardware-Accelerated GPU Scheduling (HAGS)", category: "FPS & Gaming", type: "Setting", summary: "Reduces latency and offloads VRAM management directly to the GPU.", whatItDoes: "Passes memory management responsibilities from CPU kernel to GPU, reducing frame-time spikes.", whenToUse: "Use on mid-to-high-end NVIDIA (GTX 1000+) or AMD (RX 5000+) cards.", steps: ["Open Settings → System → Display → Graphics.", "Click 'Change default graphics settings'.", "Turn ON Hardware-Accelerated GPU Scheduling and restart your PC."], url: "" },
  { id: 3, title: "Disable Variable Refresh Rate (VRR) / G-Sync per Game", category: "FPS & Gaming", type: "Setting", summary: "Prevents frame flicker on non-certified monitors during fast frame drops.", whatItDoes: "Disables hardware refresh sync if your frame rates fluctuate wildly outside the monitor range.", whenToUse: "When experiencing screen flickering in competitive shooters.", steps: ["Open NVIDIA Control Panel or AMD Software.", "Navigate to Display → G-Sync/FreeSync settings.", "Select 'Enable only for full screen mode' or disable for competitive titles."], url: "" },
  { id: 4, title: "Disable Fullscreen Optimizations", category: "FPS & Gaming", type: "Setting", summary: "Bypasses the hybrid borderless window overlay forced by Windows.", whatItDoes: "Allows games to achieve true exclusive fullscreen, dropping input lag by 5-15ms.", whenToUse: "For older games or DirectX 11 titles showing input delay.", steps: ["Right-click the game's .exe file → Properties.", "Click the 'Compatibility' tab.", "Check 'Disable fullscreen optimizations' → Apply."], url: "" },
  { id: 5, title: "Set Windows Power Plan to Ultimate Performance", category: "FPS & Gaming", type: "Setting", summary: "Forces CPU cores to run at 100% clock speeds continuously.", whatItDoes: "Disables power-saving state transitions that cause micro-stutters when launching games.", whenToUse: "For desktop gaming setups (avoid on laptops running on battery).", steps: ["Open PowerShell as Administrator.", "Paste: powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61", "Open Control Panel → Power Options → Select 'Ultimate Performance'."], url: "" },
  { id: 6, title: "Disable Xbox Game Bar and Background Recording", category: "FPS & Gaming", type: "Setting", summary: "Frees up GPU/CPU encoding capacity stolen by passive clips.", whatItDoes: "Stops background NVENC/AMD hardware video encoding when playing non-recorded games.", whenToUse: "If you use OBS or don't record background clips.", steps: ["Open Settings → Gaming → Xbox Game Bar → Turn OFF.", "Go to Captures → Turn OFF 'Record in the background while playing a game'."], url: "" },
  { id: 7, title: "Configure High Graphics Performance per App", category: "FPS & Gaming", type: "Setting", summary: "Forces Windows to use your discrete GPU over integrated graphics.", whatItDoes: "Prevents games from running on Intel UHD / AMD Radeon Integrated chips on dual-GPU laptops.", whenToUse: "When installing new games or standalone emulator executables.", steps: ["Go to Settings → System → Display → Graphics.", "Browse and select your game .exe file.", "Click Options → Choose 'High Performance' (Your dedicated GPU)."], url: "" },
  { id: 8, title: "Disable In-Game Overlays (Discord, Steam, GeForce)", category: "FPS & Gaming", type: "Setting", summary: "Reclaims 3-8 FPS and reduces background render calls.", whatItDoes: "Stops DirectX/Vulkan hook injection processes from drawing interface overlays on top of the game.", whenToUse: "If experiencing unexplained stuttering or game crashes.", steps: ["Discord: User Settings → Overlay → Disable In-game Overlay.", "Steam: Settings → In-Game → Uncheck 'Enable Steam Overlay'.", "GeForce Experience: Settings → General → Turn off In-Game Overlay."], url: "" },
  { id: 9, title: "Adjust CPU Process Priority via Process Lasso", category: "FPS & Gaming", type: "Tool", summary: "Prevents heavy background software from stealing CPU time from your game.", whatItDoes: "Enforces dynamic CPU thread management (ProBalance) to isolate game executables.", whenToUse: "When running CPU-heavy titles (e.g., Valorant, CS2, Warzone).", steps: ["Download & install Process Lasso from bitsum.com.", "Launch your game and switch back to Process Lasso.", "Right-click game.exe → CPU Priority → Always → High."], url: "https://bitsum.com" },
  { id: 10, title: "Lock Frame Rates Just Below Max Refresh Rate", category: "FPS & Gaming", type: "Setting", summary: "Eliminates screen tearing and eliminates input latency spikes.", whatItDoes: "Prevents the GPU queue from overloading when hitting 100% utilization.", whenToUse: "Always when using G-Sync or FreeSync monitors (e.g., cap at 141 FPS on a 144Hz monitor).", steps: ["Open NVIDIA Control Panel → Manage 3D Settings.", "Set 'Max Frame Rate' to 3 FPS below monitor rate (e.g., 141, 237, 357).", "Click Apply."], url: "" },
  { id: 11, title: "Enable XMP / DOCP / EXPO in BIOS", category: "RAM Optimization", type: "Setting", summary: "Runs your RAM at its advertised overclocked speeds.", whatItDoes: "By default, RAM runs at baseline speeds until the high-performance profile is selected.", whenToUse: "Mandatory on all custom PCs or upgraded RAM modules.", steps: ["Restart PC and repeatedly tap Del or F2 to enter BIOS.", "Locate XMP (Intel), DOCP (AMD AM4), or EXPO (AMD AM5).", "Select Profile 1 → Save & Exit (F10)."], url: "" },
  { id: 12, title: "Clear Standby RAM Cache with ISLC", category: "RAM Optimization", type: "Tool", summary: "Automatically purges cached standby memory before RAM fills up.", whatItDoes: "Fixes micro-stutters caused by Windows failing to release standby memory during long gaming sessions.", whenToUse: "For PCs with 8GB or 16GB RAM running heavy games.", steps: ["Download Intelligent Standby List Cleaner (ISLC) by Wagnardsoft.", "Set 'The list size is at least' to 1024MB.", "Set 'Free memory is lower than' to half your total RAM.", "Check 'Start ISLC minimized' → Click Start."], url: "https://wagnardsoft.com/forums/viewtopic.php?t=1" },
  { id: 13, title: "Set Custom Virtual Memory (Paging File)", category: "RAM Optimization", type: "Setting", summary: "Prevents Out-Of-Memory game crashes by assigning fast SSD paging space.", whatItDoes: "Allocates reserve SSD blocks to act as emergency virtual memory when physical RAM runs out.", whenToUse: "Essential for 8GB/16GB RAM setups on heavy open-world games.", steps: ["Press Win + R → type sysdm.cpl → Press Enter.", "Go to Advanced → Performance Settings → Advanced → Virtual Memory Change.", "Uncheck 'Automatically manage'. Select your fastest SSD.", "Choose Custom Size: Initial = 1.5x RAM in MB, Maximum = 3x RAM in MB."], url: "" },
  { id: 14, title: "Disable SysMain (Superfetch) Service", category: "RAM Optimization", type: "Setting", summary: "Stops excessive RAM pre-loading and high disk usage.", whatItDoes: "Stops Windows from caching unused desktop applications into RAM background pools.", whenToUse: "When RAM or Disk usage sits high idle at 90-100%.", steps: ["Press Win + R → type services.msc.", "Scroll down to find 'SysMain'.", "Right-click → Properties → Startup Type: Disabled → Click Stop → Apply."], url: "" },
  { id: 15, title: "Disable Unnecessary Startup Apps", category: "RAM Optimization", type: "Setting", summary: "Frees up 1GB-3GB RAM immediately upon booting.", whatItDoes: "Blocks auto-launch applications (Spotify, Teams, Launcher updaters) from auto-running.", whenToUse: "Perform every few months after installing new software.", steps: ["Press Ctrl + Shift + Esc to open Task Manager.", "Click the 'Startup Apps' tab.", "Right-click heavy apps → Disable."], url: "" },
  { id: 16, title: "Disable Memory Compression", category: "RAM Optimization", type: "Setting", summary: "Frees CPU cycles by stopping RAM compression routines.", whatItDoes: "Stops Windows from using CPU power to compress old RAM pages into system memory.", whenToUse: "Only if you have 32GB+ RAM and a high-end CPU.", steps: ["Open PowerShell as Administrator.", "Run command: Disable-MMAgent -MemoryCompression.", "Restart your PC."], url: "" },
  { id: 17, title: "Reduce Chrome / Edge Memory Footprint", category: "RAM Optimization", type: "Setting", summary: "Freezes inactive browser tabs automatically.", whatItDoes: "Disallocates V8 engine JS memory from tabs not viewed in 10+ minutes.", whenToUse: "If you keep 10+ browser tabs open while gaming.", steps: ["Open Chrome/Edge Settings → Performance.", "Enable 'Memory Saver' mode.", "Add essential sites to the 'Always keep active' list."], url: "" },
  { id: 18, title: "Close Background WebView2 & Helper Nodes", category: "RAM Optimization", type: "Setting", summary: "Kills invisible web renders generated by electron app launchers.", whatItDoes: "Terminates lingering embedded browser windows hosted by game launchers.", whenToUse: "After launching games from Steam, EA App, or Ubisoft Connect.", steps: ["Open Task Manager.", "Search for 'WebView2' or 'Renderer' under processes.", "End tasks running under closed launcher apps."], url: "" },
  { id: 19, title: "Clean Temporary Files with Storage Sense", category: "SSD & Disk Cleaning", type: "Setting", summary: "Automates deletion of system junk, diagnostic logs, and cache.", whatItDoes: "Safely cleans Temp, LocalAppData, and old download cache files.", whenToUse: "Enable weekly or run manually when C: drive turns red.", steps: ["Settings → System → Storage → Turn ON 'Storage Sense'.", "Click 'Run Storage Sense now'."], url: "" },
  { id: 20, title: "Delete Old Windows Installation (Windows.old)", category: "SSD & Disk Cleaning", type: "Setting", summary: "Reclaims 20GB to 40GB of C: drive space after updates.", whatItDoes: "Removes backup copies of your previous Windows installation build.", whenToUse: "7-10 days after a major Windows feature update.", steps: ["Settings → System → Storage → Temporary Files.", "Check 'Previous Windows installation(s)'.", "Click 'Remove files'."], url: "" },
  { id: 21, title: "Purge DirectX Shader Cache", category: "SSD & Disk Cleaning", type: "Setting", summary: "Clears corrupted graphics shader caches that cause game stuttering.", whatItDoes: "Deletes precompiled GPU shaders so games rebuild fresh, uncorrupted files.", whenToUse: "After updating GPU drivers or experiencing graphic artifacts.", steps: ["Open Disk Cleanup (type 'cleanmgr' in Win + R).", "Select Drive C: → Check ONLY 'DirectX Shader Cache'.", "Click OK → Delete Files."], url: "" },
  { id: 22, title: "Disable Hibernation (Delete hiberfil.sys)", category: "SSD & Disk Cleaning", type: "Setting", summary: "Instantly frees 8GB - 32GB of space on C: Drive.", whatItDoes: "Deletes the hidden root file reserved for saving RAM state during hibernation.", whenToUse: "For desktop PCs using SSDs that boot in seconds anyway.", steps: ["Open Command Prompt as Administrator.", "Type: powercfg /hibernate off", "The hiberfil.sys file is immediately removed."], url: "" },
  { id: 23, title: "Analyze Drive Space Visual Map with WizTree", category: "SSD & Disk Cleaning", type: "Tool", summary: "Locates hidden, massive files taking up space in under 3 seconds.", whatItDoes: "Directly reads the Master File Table (MFT) to generate a visual tile map of your drive.", whenToUse: "When you can't figure out what is consuming your drive storage.", steps: ["Download & launch WizTree.", "Select Drive C: → Click Scan.", "Right-click large files → Delete."], url: "https://www.diskanalyzer.com" },
  { id: 24, title: "Run TRIM Command on SSDs", category: "SSD & Disk Cleaning", type: "Setting", summary: "Maintains peak SSD read/write speeds over time.", whatItDoes: "Informs NAND flash memory blocks which data pages can be erased internally.", whenToUse: "Run manually once a month (Never defrag an SSD!).", steps: ["Press Win + S → type 'Defragment and Optimize Drives'.", "Select your SSD drive.", "Click 'Optimize' to run TRIM."], url: "" },
  { id: 25, title: "Clean Open-Source Junk with BleachBit", category: "SSD & Disk Cleaning", type: "Tool", summary: "Safe, open-source replacement for CCleaner without background telemetry.", whatItDoes: "Cleans browser caches, vacuum databases, and clears deep system logs.", whenToUse: "Once a month to clean system buildup.", steps: ["Download BleachBit.", "Check System, Deep Scan, and Web Browsers.", "Click 'Preview' → Then click 'Clean'."], url: "https://www.bleachbit.org" },
  { id: 26, title: "Clear Windows Update Cache", category: "SSD & Disk Cleaning", type: "Setting", summary: "Fixes stuck Windows updates and clears corrupted update installers.", whatItDoes: "Purges leftover download binaries from the SoftwareDistribution folder.", whenToUse: "When Windows Update gives error codes or takes up excess storage.", steps: ["Open CMD as Admin → type: net stop wuauserv.", "Delete contents of the SoftwareDistribution\\Download folder.", "Return to CMD → type: net start wuauserv."], url: "" },
  { id: 27, title: "Clear %temp% and Prefetch Files", category: "SSD & Disk Cleaning", type: "Setting", summary: "Clears residual application installers and execution traces.", whatItDoes: "Empties user temporary file dumps.", whenToUse: "Bi-weekly routine cleanup.", steps: ["Win + R → type %temp% → Select All → Delete.", "Win + R → type temp → Select All → Delete.", "Win + R → type prefetch → Select All → Delete."], url: "" },
  { id: 28, title: "Reduce Delivery Optimization Cache", category: "SSD & Disk Cleaning", type: "Setting", summary: "Prevents Windows from storing gigabytes of peer-to-peer update files.", whatItDoes: "Clears cached updates distributed to other local PCs on your network.", whenToUse: "When Windows limits storage without visible app files.", steps: ["Settings → Windows Update → Delivery Optimization.", "Turn OFF 'Allow downloads from other PCs'.", "Storage → Temporary Files → Delete 'Delivery Optimization Files'."], url: "" },
  { id: 29, title: "Run Chris Titus Tech Windows Utility", category: "Windows Debloat", type: "Tool", summary: "All-in-one open-source PowerShell script to strip Windows bloatware.", whatItDoes: "Strips pre-installed UWP apps, disables Cortana, sets services to manual, removes background agents.", whenToUse: "On fresh Windows installations or major OS setups.", steps: ["Open PowerShell / Terminal as Admin.", "Run: irm christitus.com/win | iex", "Under 'Tweaks' → Click 'Desktop' profile → Run Tweaks."], url: "https://github.com/ChrisTitusTech/winutil" },
  { id: 30, title: "Debloat Windows 11 with Win11Debloat", category: "Windows Debloat", type: "Tool", summary: "Strips Windows 11 Copilot, AI widgets, and sponsored Start Menu items.", whatItDoes: "Cleans pinned telemetry shortcuts, OneDrive auto-sync hooks, and removes AI integrations.", whenToUse: "Specifically for Windows 11 users wanting a clean setup.", steps: ["Download Win11Debloat from GitHub.", "Run application → Select 'Analyze Windows 11'.", "Apply recommended debloat fixes."], url: "https://github.com/Raphire/Win11Debloat" },
  { id: 31, title: "Disable Windows Telemetry with O&O ShutUp10++", category: "Windows Debloat", type: "Tool", summary: "Stops background analytics sent to Microsoft servers.", whatItDoes: "Disables DiagTrack services, telemetry ping schedules, and advertising IDs.", whenToUse: "Immediately after setting up Windows.", steps: ["Download O&O ShutUp10++.", "Click 'Actions' → 'Apply all recommended settings'.", "Create a system restore point and restart."], url: "https://www.oo-software.com/en/shutup10" },
  { id: 32, title: "Uninstall OneDrive (If Unused)", category: "Windows Debloat", type: "Setting", summary: "Stops background document locking and file upload cycles.", whatItDoes: "Removes OneDrive cloud sync process hooks from Windows Explorer.", whenToUse: "If you store files locally or use Google Drive/Dropbox instead.", steps: ["Settings → Apps → Installed Apps.", "Search for 'Microsoft OneDrive'.", "Click the three dots → Uninstall."], url: "" },
  { id: 33, title: "Turn Off Windows Transparency Effects", category: "Windows Debloat", type: "Setting", summary: "Reduces GPU Desktop Window Manager (dwm.exe) load.", whatItDoes: "Disables acrylic blur effects on taskbars, start menus, and app borders.", whenToUse: "For low-end integrated GPUs or low VRAM setups.", steps: ["Settings → Accessibility → Visual Effects.", "Toggle 'Transparency effects' to OFF."], url: "" },
  { id: 34, title: "Disable Start Menu Web Search & Bing Ads", category: "Windows Debloat", type: "Setting", summary: "Forces Windows search to search local PC files only.", whatItDoes: "Disables Bing web query lookups whenever you search in the Start Menu.", whenToUse: "When local file searches lag or show web ad clutter.", steps: ["Open Registry Editor (regedit).", "Navigate to Software\\Policies\\Microsoft\\Windows\\Explorer.", "Create DWORD DisableSearchBoxSuggestions = 1.", "Restart PC."], url: "" },
  { id: 35, title: "Set Non-Essential Windows Services to Manual", category: "Windows Debloat", type: "Setting", summary: "Stops background services from booting automatically.", whatItDoes: "Converts services like Print Spooler, Fax, and Remote Registry to manual trigger.", whenToUse: "To optimize low-core CPU setups.", steps: ["Press Win + R → type services.msc.", "Locate the unused service.", "Properties → Startup Type: Manual or Disabled."], url: "" },
  { id: 36, title: "Disable Widgets Board on Windows 11", category: "Windows Debloat", type: "Setting", summary: "Reclaims RAM wasted on news feed web panels.", whatItDoes: "Kills the webview background host for news and weather widgets.", whenToUse: "For Windows 11 users who don't use the Taskbar Weather Widget.", steps: ["Settings → Personalization → Taskbar.", "Toggle 'Widgets' to OFF."], url: "" },
  { id: 37, title: "Clean Install GPU Drivers using DDU", category: "GPU Drivers & Settings", type: "Tool", summary: "Completely wipes corrupted driver registry files.", whatItDoes: "Erases leftover display driver components before installing clean vendor software.", whenToUse: "When swapping GPUs, upgrading driver branches, or fixing random game crashes.", steps: ["Download Display Driver Uninstaller (DDU).", "Boot Windows into Safe Mode.", "Launch DDU → Select GPU Vendor → 'Clean and Restart'.", "Install latest official driver after reboot."], url: "https://www.wagnardsoft.com" },
  { id: 38, title: "Set NVIDIA Power Management to 'Prefer Max Performance'", category: "GPU Drivers & Settings", type: "Setting", summary: "Prevents GPU clock speeds from dropping during low-load scenes.", whatItDoes: "Locks GPU core clock speeds to performance frequencies.", whenToUse: "In competitive games where low-load drops cause frame timing latency.", steps: ["Right-click desktop → NVIDIA Control Panel.", "Manage 3D Settings → Power management mode.", "Select 'Prefer maximum performance' → Apply."], url: "" },
  { id: 39, title: "Enable Low Latency Mode (Reflex / Anti-Lag)", category: "GPU Drivers & Settings", type: "Setting", summary: "Reduces click-to-display input delay in fast shooters.", whatItDoes: "Limits render queue depth to prioritize immediate input data over frame buffering.", whenToUse: "For high-speed esports games.", steps: ["NVIDIA: Control Panel → Manage 3D Settings → Low Latency Mode: On/Ultra.", "In-game: Turn ON Reflex/Anti-Lag + Boost."], url: "" },
  { id: 40, title: "Set Texture Filtering to 'High Performance'", category: "GPU Drivers & Settings", type: "Setting", summary: "Provides a minor FPS boost on older graphics cards.", whatItDoes: "Reduces anisotropic texture sampling precision slightly in favor of speed.", whenToUse: "For entry-level or budget GPU hardware.", steps: ["NVIDIA Control Panel → Manage 3D Settings.", "Set 'Texture filtering - Quality' to 'High Performance'."], url: "" },
  { id: 41, title: "Overclock and Monitor GPU via MSI Afterburner", category: "GPU Drivers & Settings", type: "Tool", summary: "Extracts extra free GPU performance safely.", whatItDoes: "Adjusts core clock frequency, memory clock, and custom fan profiles.", whenToUse: "For gaming setups needing extra frame rate margins.", steps: ["Install MSI Afterburner.", "Set Power Limit slider to maximum.", "Increase Core Clock by +25MHz increments while testing stability."], url: "https://www.msi.com/Landing/afterburner/graphics-cards" },
  { id: 42, title: "Undervolt GPU for Lower Temps", category: "GPU Drivers & Settings", type: "Setting", summary: "Drops GPU temps without losing performance.", whatItDoes: "Reduces voltage supply curves, keeping thermal throttling from dropping clock speeds.", whenToUse: "For hot GPUs or compact ITX/laptop setups.", steps: ["Open MSI Afterburner → Ctrl+F for Voltage Curve Editor.", "Flatten target frequency curve at lower voltage.", "Apply and stress-test."], url: "" },
  { id: 43, title: "Set Threaded Optimization to 'On' (NVIDIA)", category: "GPU Drivers & Settings", type: "Setting", summary: "Allows GPU drivers to utilize multi-core CPUs efficiently.", whatItDoes: "Offloads driver CPU commands across all available processor threads.", whenToUse: "Keep enabled on modern multi-core CPUs.", steps: ["NVIDIA Control Panel → Manage 3D Settings.", "Find 'Threaded optimization' → Select ON."], url: "" },
  { id: 44, title: "Fine-Tune Hidden Settings with NVIDIA Profile Inspector", category: "GPU Drivers & Settings", type: "Tool", summary: "Exposes hidden driver settings for extreme fine-tuning.", whatItDoes: "Grants access to hidden settings like Resizable BAR overrides and low-level frame limiters.", whenToUse: "When forcing performance features not in the standard Control Panel.", steps: ["Run as Administrator.", "Select your target game profile.", "Modify hidden driver flags → Apply Changes."], url: "https://github.com/Orbmu2k/nvidiaProfileInspector" },
  { id: 45, title: "Change DNS to Cloudflare or Google", category: "Network & Latency", type: "Setting", summary: "Speeds up website loading times and domain resolution.", whatItDoes: "Bypasses slow ISP DNS servers for high-speed, secure DNS routing.", whenToUse: "On all home routers or individual PC network adapters.", steps: ["Win + R → ncpa.cpl.", "Adapter Properties → IPv4 → Properties.", "Set Primary DNS 1.1.1.1, Secondary 1.0.0.1."], url: "" },
  { id: 46, title: "Disable Nagle's Algorithm (TCP NoDelay)", category: "Network & Latency", type: "Setting", summary: "Reduces ping latency in MMORPGs and online games.", whatItDoes: "Stops Windows from bundling small packet payloads together before sending over TCP.", whenToUse: "For online gaming setups.", steps: ["Regedit → your network interface key under Tcpip\\Parameters\\Interfaces.", "Create DWORD TcpAckFrequency = 1.", "Create DWORD TCPNoDelay = 1."], url: "" },
  { id: 47, title: "Disable Network Adapter Power Saving", category: "Network & Latency", type: "Setting", summary: "Prevents random network disconnects and packet loss spikes.", whatItDoes: "Stops Windows from putting your LAN Ethernet card into sleep mode.", whenToUse: "If experiencing unexplained network drops.", steps: ["Device Manager → Network Adapters → Properties.", "Power Management tab.", "Uncheck power-saving option."], url: "" },
  { id: 48, title: "Flush DNS Cache and Reset Winsock Stack", category: "Network & Latency", type: "Setting", summary: "Fixes stale connection routes and game connection drops.", whatItDoes: "Clears local IP address mapping logs and rebuilds TCP/IP sockets.", whenToUse: "When experiencing network dropouts or lobby disconnect errors.", steps: ["CMD as Administrator.", "Type: ipconfig /flushdns", "Type: netsh winsock reset → Restart PC."], url: "" },
  { id: 49, title: "Fix Network Throttling Index", category: "Network & Latency", type: "Setting", summary: "Prevents network throughput throttling during heavy CPU usage.", whatItDoes: "Removes default Windows network limits applied during audio/video playback.", whenToUse: "If game ping spikes while listening to Discord/Spotify.", steps: ["Regedit → Multimedia\\SystemProfile.", "Set DWORD NetworkThrottlingIndex to ffffffff (Hex)."], url: "" },
  { id: 50, title: "Disable Receive Segment Coalescing (RSC)", category: "Network & Latency", type: "Setting", summary: "Fixes high latency and packet loss on network adapters.", whatItDoes: "Disables hardware packet grouping functions that cause delay.", whenToUse: "If experiencing erratic ping spikes despite fast internet speeds.", steps: ["PowerShell as Admin.", "Type: Disable-NetAdapterRsc -Name *"], url: "" },
  { id: 51, title: "Run System File Checker (SFC) and DISM Repair", category: "System Stability", type: "Setting", summary: "Fixes corrupted Windows system files causing Blue Screens.", whatItDoes: "Scans Windows system DLL stores and replaces broken core operating files.", whenToUse: "Run every few months or after improper shutdowns/power cuts.", steps: ["CMD as Administrator.", "Type: DISM.exe /Online /Cleanup-image /Restorehealth", "Type: sfc /scannow"], url: "" },
  { id: 52, title: "Check SSD Health with CrystalDiskInfo", category: "System Stability", type: "Tool", summary: "Warns of impending drive failures before losing your files.", whatItDoes: "Reads raw SSD write endurance, bad sectors, and controller temperatures.", whenToUse: "Check bi-monthly to verify drive reliability.", steps: ["Download CrystalDiskInfo.", "Verify health state reads 'Good 100%'.", "Check operating temperature stays under 60°C."], url: "https://crystalmark.info/en/software/crystaldiskinfo/" },
  { id: 53, title: "Update Motherboard BIOS & Chipset Drivers", category: "System Stability", type: "Setting", summary: "Fixes hardware bugs and enhances stability.", whatItDoes: "Applies vendor microcode updates for CPU performance and PCI-Express communication.", whenToUse: "When installing new hardware or experiencing unexplainable crashes.", steps: ["Identify motherboard model (msinfo32).", "Download latest official chipset drivers.", "Flash latest BIOS via USB through the BIOS menu."], url: "" },
  { id: 54, title: "Create a System Restore Point", category: "System Stability", type: "Setting", summary: "Safety fallback before applying system tweaks or registry modifications.", whatItDoes: "Saves a system configuration backup of registry states and drivers.", whenToUse: "MANDATORY before running debloat scripts or deep tweaks.", steps: ["Win + S → 'Create a restore point'.", "Select Drive C: → Configure → Protection ON.", "Click 'Create...' → Name it → Save."], url: "" },
  { id: 55, title: "HWiNFO64", category: "Utility Tools", type: "Tool", summary: "Comprehensive real-time hardware monitoring and diagnostic tool.", whatItDoes: "Reads raw motherboard sensors to report exact CPU/GPU thermal limits, fan speeds, power draw, and RAM timings.", whenToUse: "When stress-testing an overclock or diagnosing thermal throttling.", steps: ["Launch HWiNFO64, check 'Sensors-only'.", "Locate CPU/GPU thermal sections.", "Run a benchmark to check for 'Thermal Throttling' flags."], url: "https://www.hwinfo.com" },
  { id: 56, title: "QuickCPU", category: "Utility Tools", type: "Tool", summary: "Fine-tunes CPU core parking, frequency scaling, and power plans.", whatItDoes: "Prevents CPU cores from entering deep sleep states to maintain low input latency.", whenToUse: "When you need maximum CPU clock speeds without aggressive throttling.", steps: ["Open QuickCPU as Administrator.", "Set 'Core Parking' and 'Frequency Scaling' to 100%.", "Select 'Ultimate Performance' power plan → Apply."], url: "https://coderbag.com/product/quickcpu" },
  { id: 57, title: "Revo Uninstaller", category: "Utility Tools", type: "Tool", summary: "Deep program uninstaller that scrubs leftover registry keys and hidden folders.", whatItDoes: "Runs a program's native uninstaller then scans for remaining leftover files and registry entries.", whenToUse: "When standard Windows uninstallation leaves ghost files or fails entirely.", steps: ["Open Revo Uninstaller, locate the application.", "Click 'Uninstall', complete the default process.", "Select 'Advanced' scan mode → delete leftovers."], url: "https://www.revouninstaller.com" },
  { id: 58, title: "LatencyMon", category: "Utility Tools", type: "Tool", summary: "Diagnoses what's causing audio/input latency and stutters on your system.", whatItDoes: "Monitors DPC/ISR latency to identify which driver is causing system-wide delays.", whenToUse: "If you're getting mysterious micro-stutters or audio crackling during gameplay.", steps: ["Download LatencyMon, monitor for 5-10 minutes while idle.", "Check which driver has the highest DPC latency.", "Update or roll back that driver."], url: "https://www.resplendence.com/latencymon" },
  { id: 59, title: "Autoruns", category: "Utility Tools", type: "Tool", summary: "Official Microsoft tool showing everything that launches at startup.", whatItDoes: "Gives a far more detailed startup/task-scheduler view than Task Manager.", whenToUse: "If your PC boots slowly or you suspect hidden startup entries.", steps: ["Download from Microsoft's Sysinternals page.", "Run as Administrator.", "Go to 'Logon' tab, uncheck unrecognized entries (don't delete)."], url: "https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns" },
  { id: 60, title: "Microsoft PowerToys", category: "Utility Tools", type: "Tool", summary: "Official free Microsoft utility pack for power users.", whatItDoes: "Adds window snapping layouts (FancyZones), a bulk file renamer, a color picker, and a quick app launcher.", whenToUse: "Great general productivity add-on for any Windows setup.", steps: ["Install PowerToys from Microsoft Store or GitHub.", "Open Settings inside PowerToys.", "Enable the modules you want."], url: "https://learn.microsoft.com/en-us/windows/powertoys/" },
  { id: 61, title: "Everything (voidtools)", category: "Utility Tools", type: "Tool", summary: "Instant file search across your entire drive.", whatItDoes: "Indexes your file system in seconds and finds any file/folder near-instantly by name.", whenToUse: "When Windows Search feels slow or you need to find a file fast.", steps: ["Download Everything.", "Install, let it index your drives.", "Type any filename in the search bar to find it instantly."], url: "https://www.voidtools.com" },
  { id: 62, title: "Rufus", category: "Utility Tools", type: "Tool", summary: "Creates bootable USB drives for Windows installs and system recovery.", whatItDoes: "Formats a USB drive and writes a bootable Windows ISO to it for clean installs.", whenToUse: "When doing a fresh Windows install or need a recovery USB.", steps: ["Download Rufus and a Windows ISO.", "Insert a USB drive (8GB+), select it in Rufus.", "Select the ISO file and click 'Start'."], url: "https://rufus.ie" },
  { id: 63, title: "MemTest86", category: "System Stability", type: "Tool", summary: "Standalone RAM stress-testing utility to diagnose physical memory errors.", whatItDoes: "Executes raw pattern algorithms to test system RAM modules for hardware instability.", whenToUse: "When experiencing frequent unexplained BSODs or system crashes.", steps: ["Flash MemTest86 to a bootable USB drive.", "Boot from USB in BIOS/UEFI.", "Run the full multi-pass memory test suite."], url: "https://www.memtest86.com" },
  { id: 64, title: "TreeSize Free", category: "Utility Tools", type: "Tool", summary: "Alternative disk space visualizer, folder-by-folder breakdown.", whatItDoes: "Scans folders and shows exactly which subfolders/files are eating your storage.", whenToUse: "When you want a more detailed folder-level breakdown than a treemap view.", steps: ["Download TreeSize Free.", "Right-click a drive or folder → 'Scan with TreeSize'.", "Sort by size to find the biggest space users."], url: "https://www.jam-software.com/treesize_free" },
];

export default function PCOptimizationTools() {
  const [activeCategory, setActiveCategory] = useState("All");
  const [searchQuery, setSearchQuery] = useState("");
  const [expandedId, setExpandedId] = useState<number | null>(null);

  const filteredData = optimizationData.filter((item) => {
    const matchesCategory = activeCategory === "All" || (item.category || "").trim().toUpperCase() === activeCategory.trim().toUpperCase();
    const matchesSearch = (item.title || "").toLowerCase().includes(searchQuery.toLowerCase()) || (item.summary || "").toLowerCase().includes(searchQuery.toLowerCase()) || (item.category || "").toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  const toggleExpand = (id: number) => { setExpandedId(expandedId === id ? null : id); };

  return (
    <>
      <Header />
      <main className="min-h-screen bg-[#08090b] px-6 pt-24 pb-16 text-white font-sans">
        <div className="mx-auto max-w-6xl">
          <div className="flex flex-col gap-4 border-b border-white/10 pb-6 md:flex-row md:items-center md:justify-between">
            <div>
              <h1 className="text-4xl font-black tracking-tight text-white">PC Optimization Guide & Tools</h1>
              <p className="mt-2 text-gray-400">{optimizationData.length} verified tweaks, settings, and utilities for maximum FPS, cleaner storage, and lower latency.</p>
            </div>
            <div className="rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-right">
              <span className="text-2xl font-bold text-[#00D2FF]">{filteredData.length}</span>
              <span className="ml-2 text-xs text-gray-400">Tips Found</span>
            </div>
          </div>

          <div className="mt-6 flex items-center gap-3 rounded-xl border border-yellow-500/30 bg-yellow-500/10 p-4 text-sm text-yellow-200">
            <span className="text-xl">⚠️</span>
            <div><strong>Safety Reminder:</strong> Always create a <u>System Restore Point</u> before applying registry edits, disabling services, or running debloat scripts.</div>
          </div>

          <div className="mt-8 space-y-4">
            <input type="text" placeholder="Search by keyword (e.g. FPS, RAM, SSD, Registry, NVIDIA)..." value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} className="w-full rounded-xl border border-white/10 bg-white/5 px-5 py-3 text-sm text-white placeholder-gray-500 focus:border-[#00D2FF] focus:outline-none focus:ring-1 focus:ring-[#00D2FF]" />
            <div className="flex flex-wrap gap-2.5 pt-2">
              {categories.map((cat) => (
                <button key={cat} onClick={() => setActiveCategory(cat)} className={`rounded-full px-5 py-2 text-xs font-bold uppercase tracking-wider transition-all duration-200 ${activeCategory === cat ? "bg-[#00D2FF] text-black shadow-[0_0_15px_rgba(0,210,255,0.8)]" : "border border-white/10 bg-[#12161f] text-gray-200 hover:border-white/30 hover:bg-[#1a202c]"}`}>{cat}</button>
              ))}
            </div>
          </div>

          <div className="mt-8 grid gap-4 md:grid-cols-2">
            {filteredData.map((item) => {
              const isExpanded = expandedId === item.id;
              return (
                <div key={item.id} className="flex flex-col justify-between rounded-2xl border border-white/10 bg-[#0d111a] p-5 transition hover:border-[#00D2FF]/40">
                  <div>
                    <div className="flex items-center justify-between text-xs">
                      <span className="rounded-full bg-[#00D2FF]/20 px-3 py-1 font-bold text-[#00D2FF]">{item.category}</span>
                      <span className="rounded-md bg-white/10 px-2 py-0.5 text-gray-400">{item.type}</span>
                    </div>
                    <h3 className="mt-3 text-lg font-bold text-white">#{item.id}. {item.title}</h3>
                    <p className="mt-2 text-sm text-gray-300">{item.summary}</p>
                    {isExpanded && (
                      <div className="mt-4 space-y-3 rounded-xl border border-white/10 bg-black/50 p-4 text-xs text-gray-300">
                        <div><strong className="text-[#00D2FF]">What It Does:</strong><p className="mt-1 text-gray-400">{item.whatItDoes}</p></div>
                        <div><strong className="text-[#00D2FF]">When To Apply:</strong><p className="mt-1 text-gray-400">{item.whenToUse}</p></div>
                        <div><strong className="text-[#00D2FF]">How To Do It (Steps):</strong><ol className="mt-1.5 list-inside list-decimal space-y-1 text-gray-300">{item.steps.map((step, idx) => (<li key={idx}>{step}</li>))}</ol></div>
                      </div>
                    )}
                    {item.type === "Tool" && item.url && (
                      <a href={item.url} target="_blank" rel="noopener noreferrer" className="mt-4 inline-block rounded-lg bg-[#00D2FF] px-4 py-2 text-xs font-bold text-black transition hover:opacity-90">⬇ Download / Official Site</a>
                    )}
                  </div>
                  <div className="mt-5 border-t border-white/10 pt-3 text-right">
                    <button onClick={() => toggleExpand(item.id)} className="text-xs font-semibold text-[#00D2FF] hover:underline">{isExpanded ? "Close Guide ▲" : "View Step-By-Step Guide ▼"}</button>
                  </div>
                </div>
              );
            })}
          </div>

          {filteredData.length === 0 && (<div className="mt-12 py-12 text-center text-gray-500">No matching tips found. Try searching for broader terms like "RAM", "GPU", or "Clean".</div>)}
        </div>
      </main>
      <Footer />
    </>
  );
}