"use client";
import { useState, useEffect } from "react";
import Header from "../../Header";
import Footer from "../../Footer";
import AdsterraBanner from "../../components/AdsterraBanner";

const categories = [
  "All",
  "FPS & Gaming",
  "RAM Optimization",
  "SSD & Disk Cleaning",
  "Windows Debloat",
  "GPU Drivers & Settings",
  "CPU Tuning & Power",
  "Audio & Input Latency",
  "Network & Latency",
  "System Stability & Diagnostics",
  "Utility Tools",
];

const optimizationData = [
  { id: 1, title: "Enable Game Mode", category: "FPS & Gaming", type: "Setting", summary: "Prioritizes system resources specifically for active game processes.", whatItDoes: "Prevents background Windows Update drivers from installing and limits background apps during gameplay.", whenToUse: "Keep this permanently enabled on Windows 10 and 11.", steps: ["Press Win + I to open Settings.", "Navigate to Gaming → Game Mode.", "Toggle Game Mode to ON."], url: "" },
  { id: 2, title: "Enable Hardware-Accelerated GPU Scheduling (HAGS)", category: "FPS & Gaming", type: "Setting", summary: "Reduces latency and offloads VRAM management directly to the GPU.", whatItDoes: "Passes memory management responsibilities from CPU kernel to GPU, reducing frame-time spikes.", whenToUse: "Use on mid-to-high-end NVIDIA (GTX 1000+) or AMD (RX 5000+) cards.", steps: ["Open Settings → System → Display → Graphics.", "Click 'Change default graphics settings'.", "Turn ON Hardware-Accelerated GPU Scheduling and restart your PC."], url: "" },
  { id: 3, title: "Disable Variable Refresh Rate (VRR) / G-Sync per Game", category: "FPS & Gaming", type: "Setting", summary: "Prevents frame flicker on non-certified monitors during fast frame drops.", whatItDoes: "Disables hardware refresh sync if your frame rates fluctuate wildly outside the monitor range.", whenToUse: "When experiencing screen flickering in competitive shooters.", steps: ["Open NVIDIA Control Panel or AMD Software.", "Navigate to Display → G-Sync/FreeSync settings.", "Select 'Enable only for full screen mode' or disable for competitive titles."], url: "" },
  { id: 4, title: "Disable Fullscreen Optimizations", category: "FPS & Gaming", type: "Setting", summary: "Bypasses the hybrid borderless window overlay forced by Windows.", whatItDoes: "Allows games to achieve true exclusive fullscreen, dropping input lag by 5-15ms.", whenToUse: "For older games or DirectX 11 titles showing input delay.", steps: ["Right-click the game's .exe file → Properties.", "Click the 'Compatibility' tab.", "Check 'Disable fullscreen optimizations' → Apply."], url: "" },
  { id: 5, title: "Set Windows Power Plan to Ultimate Performance", category: "FPS & Gaming", type: "Setting", summary: "Forces CPU cores to run at 100% clock speeds continuously.", whatItDoes: "Disables power-saving state transitions that cause micro-stutters when launching games.", whenToUse: "For desktop gaming setups (avoid on laptops running on battery).", steps: ["Open PowerShell as Administrator.", "Paste: powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61", "Open Control Panel → Power Options → Select 'Ultimate Performance'."], url: "" },
  { id: 6, title: "Disable Xbox Game Bar and Background Recording", category: "FPS & Gaming", type: "Setting", summary: "Frees up GPU/CPU encoding capacity stolen by passive clips.", whatItDoes: "Stops background NVENC/AMD hardware video encoding when playing non-recorded games.", whenToUse: "If you use OBS or don't record background clips.", steps: ["Open Settings → Gaming → Xbox Game Bar → Turn OFF.", "Go to Captures → Turn OFF 'Record in the background while playing a game'."], url: "" },
  { id: 7, title: "Configure High Graphics Performance per App", category: "FPS & Gaming", type: "Setting", summary: "Forces Windows to use your discrete GPU over integrated graphics.", whatItDoes: "Prevents games from running on Intel UHD / AMD Radeon Integrated chips on dual-GPU laptops.", whenToUse: "When installing new games or standalone emulator executables.", steps: ["Go to Settings → System → Display → Graphics.", "Browse and select your game .exe file.", "Click Options → Choose 'High Performance' (Your dedicated GPU)."], url: "" },
  { id: 8, title: "Disable In-Game Overlays (Discord, Steam, GeForce)", category: "FPS & Gaming", type: "Setting", summary: "Reclaims 3-8 FPS and reduces background render calls.", whatItDoes: "Stops DirectX/Vulkan hook injection processes from drawing interface overlays on top of the game.", whenToUse: "If experiencing unexplained stuttering or game crashes.", steps: ["Discord: User Settings → Overlay → Disable In-game Overlay.", "Steam: Settings → In-Game → Uncheck 'Enable Steam Overlay'.", "GeForce Experience: Settings → General → Turn off In-Game Overlay."], url: "" },
  { id: 9, title: "Adjust CPU Process Priority via Process Lasso", category: "FPS & Gaming", type: "Tool", summary: "Prevents heavy background software from stealing CPU time from your game.", whatItDoes: "Enforces dynamic CPU thread management (ProBalance) to isolate game executables.", whenToUse: "When running CPU-heavy titles (e.g., Valorant, CS2, Warzone).", steps: ["Download & install Process Lasso from bitsum.com.", "Launch your game and switch back to Process Lasso.", "Right-click game.exe → CPU Priority → Always → High."], url: "https://bitsum.com" },
  { id: 10, title: "Lock Frame Rates Just Below Max Refresh Rate", category: "FPS & Gaming", type: "Setting", summary: "Eliminates screen tearing and eliminates input latency spikes.", whatItDoes: "Prevents the GPU queue from overloading when hitting 100% utilization.", whenToUse: "Always when using G-Sync or FreeSync monitors (e.g., cap at 141 FPS on a 144Hz monitor).", steps: ["Open NVIDIA Control Panel → Manage 3D Settings.", "Set 'Max Frame Rate' to 3 FPS below monitor rate (e.g., 141, 237, 357).", "Click Apply."], url: "" },
  { id: 11, title: "Enable XMP / DOCP / EXPO in BIOS", category: "RAM Optimization", type: "Setting", summary: "Runs your RAM at its advertised overclocked speeds.", whatItDoes: "By default, RAM runs at baseline speeds until the high-performance profile is selected.", whenToUse: "Mandatory on all custom PCs or upgraded RAM modules.", steps: ["Restart PC and repeatedly tap Del or F2 to enter BIOS.", "Locate XMP (Intel), DOCP (AMD AM4), or EXPO (AMD AM5).", "Select Profile 1 → Save & Exit (F10)."], url: "" },
  { id: 12, title: "Clear Standby RAM Cache with ISLC", category: "RAM Optimization", type: "Tool", summary: "Automatically purges cached standby memory before RAM fills up.", whatItDoes: "Fixes micro-stutters caused by Windows failing to release standby memory during long gaming sessions.", whenToUse: "For PCs with 8GB or 16GB RAM running heavy games.", steps: ["Download Intelligent Standby List Cleaner (ISLC) by Wagnardsoft.", "Set 'The list size is at least' to 1024MB.", "Set 'Free memory is lower than' to half your total RAM.", "Check 'Start ISLC minimized' → Click Start."], url: "https://wagnardsoft.com/forums/viewtopic.php?t=1" },
  { id: 13, title: "Set Custom Virtual Memory (Paging File)", category: "RAM Optimization", type: "Setting", summary: "Prevents Out-Of-Memory game crashes by assigning fast SSD paging space.", whatItDoes: "Allocates reserve SSD blocks to act as emergency virtual memory when physical RAM runs out.", whenToUse: "Essential for 8GB/16GB RAM setups on heavy open-world games.", steps: ["Press Win + R → type sysdm.cpl → Press Enter.", "Go to Advanced → Performance Settings → Advanced → Virtual Memory Change.", "Uncheck 'Automatically manage'. Select your fastest SSD.", "Choose Custom Size: Initial = 1.5x RAM in MB, Maximum = 3x RAM in MB."], url: "" },
  { id: 14, title: "Disable SysMain (Superfetch) Service", category: "RAM Optimization", type: "Setting", summary: "Stops excessive RAM pre-loading and high disk usage.", whatItDoes: "Stops Windows from caching unused desktop applications into RAM background pools.", whenToUse: "When RAM or Disk usage sits high idle at 90-100%.", steps: ["Press Win + R → type services.msc.", "Scroll down to find 'SysMain'.", "Right-click → Properties → Startup Type: Disabled → Click Stop → Apply."], url: "" },
  { id: 15, title: "Disable Unnecessary Startup Apps", category: "RAM Optimization", type: "Setting", summary: "Frees up 1GB-3GB RAM immediately upon booting.", whatItDoes: "Blocks auto-launch applications (Spotify, Teams, Launcher updaters) from auto-running.", whenToUse: "Perform every few months after installing new software.", steps: ["Press Ctrl + Shift + Esc to open Task Manager.", "Click the 'Startup Apps' tab.", "Right-click heavy apps → Disable."], url: "" },
  { id: 16, title: "Disable Memory Compression", category: "RAM Optimization", type: "Setting", summary: "Frees CPU cycles by stopping RAM compression routines.", whatItDoes: "Stops Windows from using CPU power to compress old RAM pages into system memory.", whenToUse: "Only if you have 32GB+ RAM and a high-end CPU.", steps: ["Open PowerShell as Administrator.", "Run command: Disable-MMAgent -MemoryCompression.", "Restart your PC."], url: "" },
  { id: 17, title: "Reduce Chrome / Edge Memory Footprint", category: "RAM Optimization", type: "Setting", summary: "Freezes inactive browser tabs automatically.", whatItDoes: "Disallocates V8 engine JS memory from tabs not viewed in 10+ minutes.", whenToUse: "If you keep 10+ browser tabs open while gaming.", steps: ["Open Chrome/Edge Settings → Performance.", "Enable 'Memory Saver' mode.", "Add essential sites to the 'Always keep active' list."], url: "" },
  { id: 18, title: "Close Background WebView2 & Helper Nodes", category: "RAM Optimization", type: "Setting", summary: "Kills invisible web renders generated by electron app launchers.", whatItDoes: "Terminates lingering embedded browser windows hosted by game launchers.", whenToUse: "After launching games from Steam, EA App, or Ubisoft Connect.", steps: ["Open Task Manager.", "Search for 'WebView2' or 'Renderer' under processes.", "End tasks running under closed launcher apps."], url: "" },
  { id: 19, title: "Clean Temporary Files with Storage Sense", category: "SSD & Disk Cleaning", type: "Setting", summary: "Automates deletion of system junk, diagnostic logs, and cache.", whatItDoes: "Safely cleans Temp, LocalAppData, and old download cache files.", whenToUse: "Enable weekly or run manually when C: drive turns red.", steps: ["Settings → System → Storage → Turn ON 'Storage Sense'.", "Click 'Run Storage Sense now'."], url: "" },
  { id: 20, title: "Delete Old Windows Installation (Windows.old)", category: "SSD & Disk Cleaning", type: "Setting", summary: "Reclaims 20GB to 40GB of C: drive space after updates.", whatItDoes: "Removes backup copies of your previous Windows installation build.", whenToUse: "7-10 days after a major Windows feature update.", steps: ["Settings → System → Storage → Temporary Files.", "Check 'Previous Windows installation(s)'.", "Click 'Remove files'."], url: "" },
  { id: 21, title: "Purge DirectX Shader Cache", category: "SSD & Disk Cleaning", type: "Setting", summary: "Clears corrupted graphics shader caches that cause game stuttering.", whatItDoes: "Deletes precompiled GPU shaders so games rebuild fresh, uncorrupted files.", whenToUse: "After updating GPU drivers or experiencing graphic artifacts.", steps: ["Open Disk Cleanup (type 'cleanmgr' in Win + R).", "Select Drive C: → Check ONLY 'DirectX Shader Cache'.", "Click OK → Delete Files."], url: "" },
  { id: 22, title: "Disable Hibernation (Delete hiberfil.sys)", category: "SSD & Disk Cleaning", type: "Setting", summary: "Instantly frees 8GB - 32GB of space on C: Drive.", whatItDoes: "Deletes the hidden root file reserved for saving RAM state during hibernation.", whenToUse: "For desktop PCs using SSDs that boot in seconds anyway.", steps: ["Open Command Prompt as Administrator.", "Type: powercfg /hibernate off", "The hiberfil.sys file is immediately removed."], url: "" },
  { id: 23, title: "Analyze Drive Space Visual Map with WizTree", category: "SSD & Disk Cleaning", type: "Tool", summary: "Locates hidden, massive files taking up space in under 3 seconds.", whatItDoes: "Directly reads the Master File Table (MFT) to generate a visual tile map of your drive.", whenToUse: "When you can't figure out what is consuming your drive storage.", steps: ["Download & launch WizTree.", "Select Drive C: → Click Scan.", "Right-click large files → Delete."], url: "https://www.diskanalyzer.com" },
  { id: 24, title: "Run TRIM Command on SSDs", category: "SSD & Disk Cleaning", type: "Setting", summary: "Maintains peak SSD read/write speeds over time.", whatItDoes: "Informs NAND flash memory blocks which data pages can be erased internally.", whenToUse: "Run manually once a month (Never defrag an SSD!).", steps: ["Press Win + S → type 'Defragment and Optimize Drives'.", "Select your SSD drive.", "Click 'Optimize' to run TRIM."], url: "" },
  { id: 25, title: "Clean Open-Source Junk with BleachBit", category: "SSD & Disk Cleaning", type: "Tool", summary: "Safe, open-source replacement for CCleaner without background telemetry.", whatItDoes: "Cleans browser caches, vacuum databases, and clears deep system logs.", whenToUse: "Once a month to clean system buildup.", steps: ["Download BleachBit.", "Check System, Deep Scan, and Web Browsers.", "Click 'Preview' → Then click 'Clean'."], url: "https://www.bleachbit.org" },
  { id: 26, title: "Clear Windows Update Cache", category: "SSD & Disk Cleaning", type: "Setting", summary: "Fixes stuck Windows updates and clears corrupted update installers.", whatItDoes: "Purges leftover download binaries from the SoftwareDistribution folder.", whenToUse: "When Windows Update gives error codes or takes up excess storage.", steps: ["Open CMD as Admin → type: net stop wuauserv.", "Delete contents of the SoftwareDistribution\\Download folder.", "Return to CMD → type: net start wuauserv."], url: "" },
  { id: 27, title: "Clear %temp% and Prefetch Files", category: "SSD & Disk Cleaning", type: "Setting", summary: "Clears residual application installers and execution traces.", whatItDoes: "Empties user temporary file dumps.", whenToUse: "Bi-weekly routine cleanup.", steps: ["Win + R → type %temp% → Select All → Delete.", "Win + R → type temp → Select All → Delete.", "Win + R → type prefetch → Select All → Delete."], url: "" },
  { id: 28, title: "Reduce Delivery Optimization Cache", category: "SSD & Disk Cleaning", type: "Setting", summary: "Prevents Windows from storing gigabytes of peer-to-peer update files.", whatItDoes: "Clears cached updates distributed to other local PCs on your network.", whenToUse: "When Windows limits storage without visible app files.", steps: ["Settings → Windows Update → Delivery Optimization.", "Turn OFF 'Allow downloads from other PCs'.", "Storage → Temporary Files → Delete 'Delivery Optimization Files'."], url: "" },
  { id: 29, title: "Run Chris Titus Tech Windows Utility", category: "Windows Debloat", type: "Tool", summary: "All-in-one open-source PowerShell script to strip Windows bloatware.", whatItDoes: "Strips pre-installed UWP apps, disables Cortana, sets services to manual, removes background agents.", whenToUse: "On fresh Windows installations or major OS setups.", steps: ["Open PowerShell / Terminal as Admin.", "Run: irm christitus.com/win | iex", "Under 'Tweaks' → Click 'Desktop' profile → Run Tweaks."], url: "https://github.com/ChrisTitusTech/winutil" },
  { id: 30, title: "Debloat Windows 11 with Win11Debloat", category: "Windows Debloat", type: "Tool", summary: "Strips Windows 11 Copilot, AI widgets, and sponsored Start Menu items.", whatItDoes: "Cleans pinned telemetry shortcuts, OneDrive auto-sync hooks, and removes AI integrations.", whenToUse: "Specifically for Windows 11 users wanting a clean setup.", steps: ["Download Win11Debloat from GitHub.", "Run application → Select 'Analyze Windows 11'.", "Apply recommended debloat fixes."], url: "https://github.com/Raphire/Win11Debloat" },
  { id: 31, title: "Disable Windows Telemetry with O&O ShutUp10++", category: "Windows Debloat", type: "Tool", summary: "Stops background analytics sent to Microsoft servers.", whatItDoes: "Disables DiagTrack services, telemetry ping schedules, and advertising IDs.", whenToUse: "Immediately after setting up Windows.", steps: ["Download O&O ShutUp10++.", "Click 'Actions' → 'Apply all recommended settings'.", "Create a system restore point and restart."], url: "https://www.oo-software.com/en/shutup10" },
  { id: 32, title: "Uninstall OneDrive (If Unused)", category: "Windows Debloat", type: "Setting", summary: "Stops background document locking and file upload cycles.", whatItDoes: "Removes OneDrive cloud sync process hooks from Windows Explorer.", whenToUse: "If you store files locally or use Google Drive/Dropbox instead.", steps: ["Settings → Apps → Installed Apps.", "Search for 'Microsoft OneDrive'.", "Click the three dots → Uninstall."], url: "" },
  { id: 33, title: "Turn Off Windows Transparency Effects", category: "Windows Debloat", type: "Setting", summary: "Reduces GPU Desktop Window Manager (dwm.exe) load.", whatItDoes: "Disables acrylic blur effects on taskbars, start menus, and app borders.", whenToUse: "For low-end integrated GPUs or low VRAM setups.", steps: ["Settings → Accessibility → Visual Effects.", "Toggle 'Transparency effects' to OFF."], url: "" },
  { id: 34, title: "Disable Start Menu Web Search & Bing Ads", category: "Windows Debloat", type: "Setting", summary: "Forces Windows search to search local PC files only.", whatItDoes: "Disables Bing web query lookups whenever you search in the Start Menu.", whenToUse: "When local file searches lag or show web ad clutter.", steps: ["Open Registry Editor (regedit).", "Navigate to Software\\Policies\\Microsoft\\Windows\\Explorer.", "Create DWORD DisableSearchBoxSuggestions = 1.", "Restart PC."], url: "" },
  { id: 35, title: "Set Non-Essential Windows Services to Manual", category: "Windows Debloat", type: "Setting", summary: "Stops background services from booting automatically.", whatItDoes: "Converts services like Print Spooler, Fax, and Remote Registry to manual trigger.", whenToUse: "To optimize low-core CPU setups.", steps: ["Press Win + R → type services.msc.", "Locate the unused service.", "Properties → Startup Type: Manual or Disabled."], url: "" },
  { id: 36, title: "Disable Widgets Board on Windows 11", category: "Windows Debloat", type: "Setting", summary: "Reclaims RAM wasted on news feed web panels.", whatItDoes: "Kills the webview background host for news and weather widgets.", whenToUse: "For Windows 11 users who don't use the Taskbar Weather Widget.", steps: ["Settings → Personalization → Taskbar.", "Toggle 'Widgets' to OFF."], url: "" },
  { id: 37, title: "Clean Install GPU Drivers using DDU", category: "GPU Drivers & Settings", type: "Tool", summary: "Completely wipes corrupted driver registry files.", whatItDoes: "Erases leftover display driver components before installing clean vendor software.", whenToUse: "When swapping GPUs, upgrading driver branches, or fixing random game crashes.", steps: ["Download Display Driver Uninstaller (DDU).", "Boot Windows into Safe Mode.", "Launch DDU → Select GPU Vendor → 'Clean and Restart'.", "Install latest official driver after reboot."], url: "https://www.wagnardsoft.com" },
  { id: 38, title: "Set NVIDIA Power Management to 'Prefer Max Performance'", category: "GPU Drivers & Settings", type: "Setting", summary: "Prevents GPU clock speeds from dropping during low-load scenes.", whatItDoes: "Locks GPU core clock speeds to performance frequencies.", whenToUse: "In competitive games where low-load drops cause frame timing latency.", steps: ["Right-click desktop → NVIDIA Control Panel.", "Manage 3D Settings → Power management mode.", "Select 'Prefer maximum performance' → Apply."], url: "" },
  { id: 39, title: "Enable Low Latency Mode (Reflex / Anti-Lag)", category: "GPU Drivers & Settings", type: "Setting", summary: "Reduces click-to-display input delay in fast shooters.", whatItDoes: "Limits render queue depth to prioritize immediate input data over frame buffering.", whenToUse: "For high-speed esports games.", steps: ["NVIDIA: Control Panel → Manage 3D Settings → Low Latency Mode: On/Ultra.", "In-game: Turn ON Reflex/Anti-Lag + Boost."], url: "" },
  { id: 40, title: "Set Texture Filtering to 'High Performance'", category: "GPU Drivers & Settings", type: "Setting", summary: "Provides a minor FPS boost on older graphics cards.", whatItDoes: "Reduces anisotropic texture sampling precision slightly in favor of speed.", whenToUse: "For entry-level or budget GPU hardware.", steps: ["NVIDIA Control Panel → Manage 3D Settings.", "Set 'Texture filtering - Quality' to 'High Performance'."], url: "" },
  { id: 41, title: "Overclock and Monitor GPU via MSI Afterburner", category: "GPU Drivers & Settings", type: "Tool", summary: "Extracts extra free GPU performance safely.", whatItDoes: "Adjusts core clock frequency, memory clock, and custom fan profiles.", whenToUse: "For gaming setups needing extra frame rate margins.", steps: ["Install MSI Afterburner.", "Set Power Limit slider to maximum.", "Increase Core Clock by +25MHz increments while testing stability."], url: "https://www.msi.com/Landing/afterburner/graphics-cards" },
  { id: 42, title: "Undervolt GPU for Lower Temps", category: "GPU Drivers & Settings", type: "Setting", summary: "Drops GPU temps without losing performance.", whatItDoes: "Reduces voltage supply curves, keeping thermal throttling from dropping clock speeds.", whenToUse: "For hot GPUs or compact ITX/laptop setups.", steps: ["Open MSI Afterburner → Ctrl+F for Voltage Curve Editor.", "Flatten target frequency curve at lower voltage.", "Apply and stress-test."], url: "" },
  { id: 43, title: "Set Threaded Optimization to 'On' (NVIDIA)", category: "GPU Drivers & Settings", type: "Setting", summary: "Allows GPU drivers to utilize multi-core CPUs efficiently.", whatItDoes: "Offloads driver CPU commands across all available processor threads.", whenToUse: "Keep enabled on modern multi-core CPUs.", steps: ["NVIDIA Control Panel → Manage 3D Settings.", "Find 'Threaded optimization' → Select ON."], url: "" },
  { id: 44, title: "Fine-Tune Hidden Settings with NVIDIA Profile Inspector", category: "GPU Drivers & Settings", type: "Tool", summary: "Exposes hidden driver settings for extreme fine-tuning.", whatItDoes: "Grants access to hidden settings like Resizable BAR overrides and low-level frame limiters.", whenToUse: "When forcing performance features not in the standard Control Panel.", steps: ["Run as Administrator.", "Select your target game profile.", "Modify hidden driver flags → Apply Changes."], url: "https://github.com/Orbmu2k/nvidiaProfileInspector" },
  { id: 45, title: "Change DNS to Cloudflare or Google", category: "Network & Latency", type: "Setting", summary: "Speeds up website loading times and domain resolution.", whatItDoes: "Bypasses slow ISP DNS servers for high-speed, secure DNS routing.", whenToUse: "On all home routers or individual PC network adapters.", steps: ["Win + R → ncpa.cpl.", "Adapter Properties → IPv4 → Properties.", "Set Primary DNS 1.1.1.1, Secondary 1.0.0.1."], url: "" },
  { id: 46, title: "Disable Nagle's Algorithm (TCP NoDelay)", category: "Network & Latency", type: "Setting", summary: "Reduces ping latency in MMORPGs and online games.", whatItDoes: "Stops Windows from bundling small packet payloads together before sending over TCP.", whenToUse: "For online gaming setups.", steps: ["Regedit → your network interface key under Tcpip\\Parameters\\Interfaces.", "Create DWORD TcpAckFrequency = 1.", "Create DWORD TCPNoDelay = 1."], url: "" },
  { id: 47, title: "Disable Network Adapter Power Saving", category: "Network & Latency", type: "Setting", summary: "Prevents random network disconnects and packet loss spikes.", whatItDoes: "Stops Windows from putting your LAN Ethernet card into sleep mode.", whenToUse: "If experiencing unexplained network drops.", steps: ["Device Manager → Network Adapters → Properties.", "Power Management tab.", "Uncheck power-saving option."], url: "" },
  { id: 48, title: "Flush DNS Cache and Reset Winsock Stack", category: "Network & Latency", type: "Setting", summary: "Fixes stale connection routes and game connection drops.", whatItDoes: "Clears local IP address mapping logs and rebuilds TCP/IP sockets.", whenToUse: "When experiencing network dropouts or lobby disconnect errors.", steps: ["CMD as Administrator.", "Type: ipconfig /flushdns", "Type: netsh winsock reset → Restart PC."], url: "" },
  { id: 49, title: "Fix Network Throttling Index", category: "Network & Latency", type: "Setting", summary: "Prevents network throughput throttling during heavy CPU usage.", whatItDoes: "Removes default Windows network limits applied during audio/video playback.", whenToUse: "If game ping spikes while listening to Discord/Spotify.", steps: ["Regedit → Multimedia\\SystemProfile.", "Set DWORD NetworkThrottlingIndex to ffffffff (Hex)."], url: "" },
  { id: 50, title: "Disable Receive Segment Coalescing (RSC)", category: "Network & Latency", type: "Setting", summary: "Fixes high latency and packet loss on network adapters.", whatItDoes: "Disables hardware packet grouping functions that cause delay.", whenToUse: "If experiencing erratic ping spikes despite fast internet speeds.", steps: ["PowerShell as Admin.", "Type: Disable-NetAdapterRsc -Name *"], url: "" },
  { id: 51, title: "Run System File Checker (SFC) and DISM Repair", category: "System Stability", type: "Setting", summary: "Fixes corrupted Windows system files causing Blue Screens.", whatItDoes: "Scans Windows system DLL stores and replaces broken core operating files.", whenToUse: "Run every few months or after improper shutdowns/power cuts.", steps: ["CMD as Administrator.", "Type: DISM.exe /Online /Cleanup-image /Restorehealth", "Type: sfc /scannow"], url: "" },
  { id: 52, title: "Check SSD Health with CrystalDiskInfo", category: "System Stability", type: "Tool", summary: "Warns of impending drive failures before losing your files.", whatItDoes: "Reads raw SSD write endurance, bad sectors, and controller temperatures.", whenToUse: "Check bi-monthly to verify drive reliability.", steps: ["Download CrystalDiskInfo.", "Verify health state reads 'Good 100%'.", "Check operating temperature stays under 60°C."], url: "https://crystalmark.info/en/software/crystaldiskinfo/" },
  { id: 53, title: "Update Motherboard BIOS & Chipset Drivers", category: "System Stability", type: "Setting", summary: "Fixes hardware bugs and enhances stability.", whatItDoes: "Applies vendor microcode updates for CPU performance and PCI-Express communication.", whenToUse: "When installing new hardware or experiencing unexplainable crashes.", steps: ["Identify motherboard model (msinfo32).", "Download latest official chipset drivers.", "Flash latest BIOS via USB through the BIOS menu."], url: "" },
  { id: 54, title: "Create a System Restore Point", category: "System Stability", type: "Setting", summary: "Safety fallback before applying system tweaks or registry modifications.", whatItDoes: "Saves a system configuration backup of registry states and drivers.", whenToUse: "MANDATORY before running debloat scripts or deep tweaks.", steps: ["Win + S → 'Create a restore point'.", "Select Drive C: → Configure → Protection ON.", "Click 'Create...' → Name it → Save."], url: "" },
  { id: 55, title: "HWiNFO64", category: "Utility Tools", type: "Tool", summary: "Comprehensive real-time hardware monitoring and diagnostic tool.", whatItDoes: "Reads raw motherboard sensors to report exact CPU/GPU thermal limits, fan speeds, power draw, and RAM timings.", whenToUse: "When stress-testing an overclock or diagnosing thermal throttling.", steps: ["Launch HWiNFO64, check 'Sensors-only'.", "Locate CPU/GPU thermal sections.", "Run a benchmark to check for 'Thermal Throttling' flags."], url: "https://www.hwinfo.com" },
  { id: 56, title: "QuickCPU", category: "Utility Tools", type: "Tool", summary: "Fine-tunes CPU core parking, frequency scaling, and power plans.", whatItDoes: "Prevents CPU cores from entering deep sleep states to maintain low input latency.", whenToUse: "When you need maximum CPU clock speeds without aggressive throttling.", steps: ["Open QuickCPU as Administrator.", "Set 'Core Parking' and 'Frequency Scaling' to 100%.", "Select 'Ultimate Performance' power plan → Apply."], url: "https://coderbag.com/product/quickcpu" },
  { id: 57, title: "Revo Uninstaller", category: "Utility Tools", type: "Tool", summary: "Deep program uninstaller that scrubs leftover registry keys and hidden folders.", whatItDoes: "Runs a program's native uninstaller then scans for remaining leftover files and registry entries.", whenToUse: "When standard Windows uninstallation leaves ghost files or fails entirely.", steps: ["Open Revo Uninstaller, locate the application.", "Click 'Uninstall', complete the default process.", "Select 'Advanced' scan mode → delete leftovers."], url: "https://www.revouninstaller.com" },
  { id: 58, title: "LatencyMon", category: "Utility Tools", type: "Tool", summary: "Diagnoses what's causing audio/input latency and stutters on your system.", whatItDoes: "Monitors DPC/ISR latency to identify which driver is causing system-wide delays.", whenToUse: "If you're getting mysterious micro-stutters or audio crackling during gameplay.", steps: ["Download LatencyMon, monitor for 5-10 minutes while idle.", "Check which driver has the highest DPC latency.", "Update or roll back that driver."], url: "https://www.resplendence.com/latencymon" },
  { id: 59, title: "Autoruns", category: "Utility Tools", type: "Tool", summary: "Official Microsoft tool showing everything that launches at startup.", whatItDoes: "Gives a far more detailed startup/task-scheduler view than Task Manager.", whenToUse: "If your PC boots slowly or you suspect hidden startup entries.", steps: ["Download from Microsoft's Sysinternals page.", "Run as Administrator.", "Go to 'Logon' tab, uncheck unrecognized entries (don't delete)."], url: "https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns" },
  { id: 60, title: "Microsoft PowerToys", category: "Utility Tools", type: "Tool", summary: "Official free Microsoft utility pack for power users.", whatItDoes: "Adds window snapping layouts (FancyZones), a bulk file renamer, a color picker, and a quick app launcher.", whenToUse: "Great general productivity add-on for any Windows setup.", steps: ["Install PowerToys from Microsoft Store or GitHub.", "Open Settings inside PowerToys.", "Enable the modules you want."], url: "https://learn.microsoft.com/en-us/windows/powertoys/" },
  { id: 61, title: "Everything (voidtools)", category: "Utility Tools", type: "Tool", summary: "Instant file search across your entire drive.", whatItDoes: "Indexes your file system in seconds and finds any file/folder near-instantly by name.", whenToUse: "When Windows Search feels slow or you need to find a file fast.", steps: ["Download Everything.", "Install, let it index your drives.", "Type any filename in the search bar to find it instantly."], url: "https://www.voidtools.com" },
  { id: 62, title: "Rufus", category: "Utility Tools", type: "Tool", summary: "Creates bootable USB drives for Windows installs and system recovery.", whatItDoes: "Formats a USB drive and writes a bootable Windows ISO to it for clean installs.", whenToUse: "When doing a fresh Windows install or need a recovery USB.", steps: ["Download Rufus and a Windows ISO.", "Insert a USB drive (8GB+), select it in Rufus.", "Select the ISO file and click 'Start'."], url: "https://rufus.ie" },
  { id: 63, title: "MemTest86", category: "System Stability", type: "Tool", summary: "Standalone RAM stress-testing utility to diagnose physical memory errors.", whatItDoes: "Executes raw pattern algorithms to test system RAM modules for hardware instability.", whenToUse: "When experiencing frequent unexplained BSODs or system crashes.", steps: ["Flash MemTest86 to a bootable USB drive.", "Boot from USB in BIOS/UEFI.", "Run the full multi-pass memory test suite."], url: "https://www.memtest86.com" },
  { id: 64, title: "TreeSize Free", category: "Utility Tools", type: "Tool", summary: "Alternative disk space visualizer, folder-by-folder breakdown.", whatItDoes: "Scans folders and shows exactly which subfolders/files are eating your storage.", whenToUse: "When you want a more detailed folder-level breakdown than a treemap view.", steps: ["Download TreeSize Free.", "Right-click a drive or folder → 'Scan with TreeSize'.", "Sort by size to find the biggest space users."], url: "https://www.jam-software.com/treesize_free" },
  { id: 65, title: "Purge Standby Memory with RamMap", category: "RAM Optimization", type: "Tool", summary: "Instantly empties modified and standby memory lists without rebooting.", whatItDoes: "Flushes standby cache pages that Windows refuses to release to active game processes.", whenToUse: "When games stutter or crash with 'out of memory' despite having free RAM.", steps: ["Download RamMap from Microsoft Sysinternals.", "Run RamMap as Administrator.", "Click 'Empty' in the top menu bar → Select 'Empty Standby List'.", "Optionally select 'Empty Working Sets'."], url: "https://learn.microsoft.com/en-us/sysinternals/downloads/rammap" },
  { id: 66, title: "Schedule Automated EmptyStandbyList Task", category: "RAM Optimization", type: "Setting", summary: "Automates background RAM clearing every 5 minutes.", whatItDoes: "Silently calls Windows memory management API to clear standby list on a timer.", whenToUse: "For PCs with 8GB or 16GB RAM running memory-intensive open world games.", steps: ["Download EmptyStandbyList.exe and place it in C:\\Windows.", "Open Task Scheduler as Administrator.", "Create a new task running with Highest Privileges, triggering every 5 minutes indefinitely.", "Set action: Start a program → C:\\Windows\\EmptyStandbyList.exe."], url: "" },
  { id: 67, title: "Windows Memory Diagnostic Tool (mdsched)", category: "RAM Optimization", type: "Setting", summary: "Built-in Windows hardware RAM tester for memory corruption.", whatItDoes: "Boots into a pre-Windows environment to run deep memory read/write algorithms across all RAM sticks.", whenToUse: "When experiencing random memory management BSODs (MEMORY_MANAGEMENT or CRITICAL_PROCESS_DIED).", steps: ["Press Win + R → type mdsched.exe → Press Enter.", "Choose 'Restart now and check for problems'.", "Allow your PC to reboot and complete the multi-pass hardware memory scan."], url: "" },
  { id: 68, title: "Disable Connected User Experiences & Telemetry (DiagTrack)", category: "RAM Optimization", type: "Setting", summary: "Stops telemetry background service from consuming 100MB-300MB RAM.", whatItDoes: "Stops Microsoft background tracking service from constantly writing event logs to memory.", whenToUse: "To reclaim RAM and CPU cycles on all Windows systems.", steps: ["Press Win + R → type services.msc.", "Find 'Connected User Experiences and Telemetry'.", "Right-click → Properties → Startup type: Disabled → Click Stop → Apply."], url: "" },
  { id: 69, title: "Disable Core Isolation (Memory Integrity) for Gaming", category: "CPU Tuning & Power", type: "Setting", summary: "Reclaims 5% to 12% CPU gaming performance on Windows 11.", whatItDoes: "Disables virtualization-based security (VBS) which runs Windows inside a hypervisor sandbox.", whenToUse: "On dedicated gaming rigs where maximum gaming FPS is desired.", steps: ["Open Windows Security → Device Security.", "Click 'Core isolation details'.", "Toggle 'Memory integrity' to OFF.", "Restart your PC."], url: "" },
  { id: 70, title: "Unpark CPU Cores with ParkControl", category: "CPU Tuning & Power", type: "Tool", summary: "Prevents Windows from putting secondary CPU cores into low-power parking states.", whatItDoes: "Disables aggressive core parking so all physical and logical cores respond instantly to game threads.", whenToUse: "When experiencing frame-time drops in CPU-bound competitive games.", steps: ["Download & install ParkControl by Bitsum.", "Select 'Bredos Bitsum Highest Performance' or your active power profile.", "Set CPU Parking to 'Disabled' (100%) and Frequency Scaling to 100%.", "Click Apply and check 'Make active'."], url: "https://bitsum.com/parkcontrol/" },
  { id: 71, title: "Undervolt & Tweak Intel CPUs with ThrottleStop", category: "CPU Tuning & Power", type: "Tool", summary: "Eliminates thermal throttling and lowers CPU temperatures by 5-15°C.", whatItDoes: "Adjusts CPU voltage offsets (FIVR) and modifies Power Limits (PL1/PL2) for sustained clock speeds.", whenToUse: "For Intel gaming laptops and hot desktop CPUs hitting 90°C+.", steps: ["Download ThrottleStop and extract to a folder.", "Open FIVR window → Check 'Unlock Adjustable Voltage'.", "Apply a conservative negative offset (e.g., -50mV on CPU Core and Cache).", "Test with Cinebench or TS Bench for stability."], url: "https://www.techpowerup.com/download/techpowerup-throttlestop/" },
  { id: 72, title: "Optimize AMD Ryzen Curve Optimizer (PBO)", category: "CPU Tuning & Power", type: "Setting", summary: "Boosts AMD Ryzen clocks higher while drawing less voltage.", whatItDoes: "Applies per-core or all-core undervolt curves to AMD Zen 3 and Zen 4 processors.", whenToUse: "For Ryzen 5000, 7000, and 9000 series desktop processors.", steps: ["Enter BIOS (Del/F2 during boot).", "Navigate to Precision Boost Overdrive (PBO) → Advanced.", "Select Curve Optimizer → 'All Cores' → 'Negative' offset.", "Start with -15 to -20 and test stability using OCCT."], url: "" },
  { id: 73, title: "Disable High Precision Event Timer (HPET) in Windows", category: "CPU Tuning & Power", type: "Setting", summary: "Reduces micro-stuttering and micro-latency in high FPS games.", whatItDoes: "Forces Windows to use the CPU's internal TSC timer rather than the slower motherboard HPET timer.", whenToUse: "When seeking minimum frame time variance in esports titles.", steps: ["Open Device Manager (Win + X → Device Manager).", "Expand 'System devices'.", "Right-click 'High precision event timer' → Disable device.", "Open CMD as Admin and run: bcdedit /deletevalue useplatformclock (if present)."], url: "" },
  { id: 74, title: "Disable CPU C-States in BIOS (Desktops Only)", category: "CPU Tuning & Power", type: "Setting", summary: "Eliminates micro-delays caused by CPU power state sleep transitions.", whatItDoes: "Prevents CPU cores from dropping down into deep sleep (C6/C7/C8) power-saving idle states.", whenToUse: "For competitive esports desktop rigs looking for lowest possible input latency.", steps: ["Restart PC and enter BIOS (Del/F2).", "Locate CPU Power Management or Advanced CPU Configuration.", "Find 'Global C-States' or 'C-State Support' → Set to Disabled.", "Save and reboot (F10)."], url: "" },
  { id: 75, title: "Tune Laptop APU with Universal x86 Tuning Utility (UXTU)", category: "CPU Tuning & Power", type: "Tool", summary: "Unlocks custom power limits and thermal targets for AMD & Intel mobile CPUs.", whatItDoes: "Adjusts TDP limits, sustained wattage, and temperature ceilings on gaming handhelds and laptops.", whenToUse: "For ASUS ROG Ally, Lenovo Legion Go, or AMD Ryzen thin-and-light laptops.", steps: ["Download Universal x86 Tuning Utility from GitHub.", "Select your APU generation preset (Eco, Balance, or Extreme).", "Adjust Temperature Limit or TDP Wattage slider to match your cooler.", "Apply profile before launching games."], url: "https://github.com/JamesCJ60/Universal-x86-Tuning-Utility" },
  { id: 76, title: "Set Processor Affinity for Problematic Games", category: "CPU Tuning & Power", type: "Setting", summary: "Forces games to run only on high-performance P-cores or single CCDs.", whatItDoes: "Prevents hybrid Intel CPUs (P-cores vs E-cores) or dual-CCD Ryzen CPUs from thread hopping.", whenToUse: "If an older game runs poorly on Intel 12th/13th/14th gen or Ryzen 7900X/7950X.", steps: ["Launch the game, open Task Manager (Ctrl+Shift+Esc).", "Go to Details tab → Right-click the game's .exe → Set Affinity.", "Uncheck efficiency cores (E-cores) or secondary CCD cores, leaving only performance cores checked."], url: "" },
  { id: 77, title: "Configure FilterKeys for Zero Keyboard Input Lag", category: "Audio & Input Latency", type: "Tool", summary: "Eliminates keyboard repeat delay and repeat rate latency in gaming.", whatItDoes: "Tweaks Windows accessibility registry flags to drop key-press repeat delay to single-digit milliseconds.", whenToUse: "Essential for rhythm games (osu!), competitive shooters (CS2, Valorant), and fast typists.", steps: ["Download FilterKeys Setter (FilterKeysSetter.exe).", "Set Repeat Delay to 150ms (or 130ms).", "Set Repeat Rate to 15ms (or 20ms).", "Check 'On' and click Apply."], url: "https://github.com/archta/FilterKeysSetter" },
  { id: 78, title: "Disable 'Enhance Pointer Precision' (Mouse Acceleration)", category: "Audio & Input Latency", type: "Setting", summary: "Ensures 1:1 true physical mouse tracking without artificial acceleration.", whatItDoes: "Stops Windows from altering mouse cursor distance based on hand speed rather than raw displacement.", whenToUse: "Mandatory for all PC gamers and precision mouse users.", steps: ["Press Win + R → type main.cpl → Press Enter.", "Click the 'Pointer Options' tab.", "Uncheck 'Enhance pointer precision'.", "Ensure pointer speed slider is at the exact center (6/11 notch) → Apply."], url: "" },
  { id: 79, title: "Enable MSI Mode on GPU & Network Card (MSI Utility v3)", category: "Audio & Input Latency", type: "Tool", summary: "Converts legacy IRQ pin interrupts to fast Message Signaled-Based Interrupts.", whatItDoes: "Eliminates interrupt conflicts and lowers input latency between GPU, NIC, and CPU.", whenToUse: "When optimizing competitive gaming PCs for lowest system DPC latency.", steps: ["Download MSI Utility v3 and run as Administrator.", "Locate your Graphics Card in the list → Check the 'MSI' box.", "Set Interrupt Priority to 'High' (or Undefined).", "Click Apply at the top right and restart PC."], url: "https://forums.guru3d.com/threads/windows-line-based-vs-message-signaled-based-interrupts-msi-tool.378044/" },
  { id: 80, title: "Disable Exclusive Audio Mode to Fix Game Audio Stutter", category: "Audio & Input Latency", type: "Setting", summary: "Prevents external audio drivers from locking your sound card and crashing games.", whatItDoes: "Allows multiple applications (Discord, Spotify, Game) to share the audio stream without buffer dropouts.", whenToUse: "If game audio cuts out, pops, or stutters during Discord voice calls.", steps: ["Press Win + R → type mmsys.cpl → Press Enter.", "Right-click your active Playback Device → Properties.", "Go to Advanced tab → Uncheck 'Allow applications to take exclusive control of this device'.", "Click Apply."], url: "" },
  { id: 81, title: "Turn Off Windows Spatial Audio & Sound Enhancements", category: "Audio & Input Latency", type: "Setting", summary: "Eliminates sound processing latency and provides raw positional audio.", whatItDoes: "Disables Windows software DSP virtualization algorithms that add 15-30ms audio lag.", whenToUse: "For competitive shooters where hearing exact footstep direction instantly is crucial.", steps: ["Open Settings → System → Sound.", "Click on your current output device.", "Set 'Audio enhancements' to OFF.", "Set 'Spatial sound' to OFF."], url: "" },
  { id: 82, title: "Disable USB Selective Suspend & Host Power Saving", category: "Audio & Input Latency", type: "Setting", summary: "Prevents gaming mice, keyboards, and USB DACs from randomly disconnecting.", whatItDoes: "Stops Windows power manager from cycling USB hubs into low-voltage sleep during brief inactivity.", whenToUse: "If your mouse disconnects for 1 second or audio interface crackles.", steps: ["Press Win + X → Device Manager.", "Expand 'Universal Serial Bus controllers'.", "Right-click each 'USB Root Hub' → Properties → Power Management tab.", "Uncheck 'Allow the computer to turn off this device to save power'."], url: "" },
  { id: 83, title: "Fix Realtek Audio Power Management Registry Sleep", category: "Audio & Input Latency", type: "Setting", summary: "Eliminates the annoying 'pop' or delay when audio starts playing through headphones.", whatItDoes: "Disables the 10-second driver timeout that puts the onboard Realtek audio codec to sleep.", whenToUse: "If you hear a click/pop sound right before videos or notification sounds play.", steps: ["Open regedit → HKEY_CURRENT_USER\\Software\\Realtek\\Audio\\RtkNGUI64\\PowerMgnt.", "Set Enabled to 0.", "Navigate to HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Class\\{4d36e96c-e325-11ce-bfc1-08002be10318}\\0000\\PowerSettings.", "Set ConservationIdleTime, IdlePowerState, and PerformanceIdleTime to ff ff ff ff."], url: "" },
  { id: 84, title: "Cap FPS with RivaTuner Statistics Server (RTSS)", category: "FPS & Gaming", type: "Tool", summary: "Provides the smoothest, flattest frame-time graph with zero micro-stutter.", whatItDoes: "Uses CPU spin-waiting frame limiting that provides significantly more consistent frame pacing than in-game limiters.", whenToUse: "When in-game FPS caps feel jittery or inconsistent on high refresh monitors.", steps: ["Install RTSS (included with MSI Afterburner or standalone).", "Set 'Framerate limit' to your desired number (e.g. 141 for 144Hz, 237 for 240Hz).", "Set 'Framerate limiter' mode to 'Front Edge' or 'Async'.", "Keep RTSS running minimized."], url: "https://www.guru3d.com/download/rtss-rivatuner-statistics-server-download/" },
  { id: 85, title: "Enable Resizable BAR / AMD Smart Access Memory (SAM)", category: "FPS & Gaming", type: "Setting", summary: "Gives CPU full access to entire GPU VRAM pool for 5-15% FPS gains.", whatItDoes: "Replaces the 256MB PCIe transfer window with unlimited access to full VRAM.", whenToUse: "On modern systems (Intel 10th+ Gen or AMD Ryzen 3000+ with RTX 30/40 or Radeon RX 6000/7000).", steps: ["Boot into BIOS (Del/F2).", "Enable 'Above 4G Decoding'.", "Enable 'Re-Size BAR Support' (or Smart Access Memory).", "Save & Exit. Check GPU-Z to verify Resizable BAR is Enabled."], url: "" },
  { id: 86, title: "Set Timer Resolution to 0.5ms (TimerResolution Tool)", category: "FPS & Gaming", type: "Tool", summary: "Lowers Windows system clock resolution from 15.6ms down to 0.5ms.", whatItDoes: "Forces system-wide high-frequency timer interrupts, smoothing input polling and frame dispatch.", whenToUse: "Before launching competitive FPS games.", steps: ["Download TimerResolution.", "Run application before opening your game.", "Click 'Maximum' button to lock system timer at 0.500ms.", "Leave running in background while playing."], url: "https://vvvv.org/contribution/windows-timer-resolution" },
  { id: 87, title: "Purge Steam Shader Pre-Caching and Download Cache", category: "FPS & Gaming", type: "Setting", summary: "Fixes game launch crashes, missing textures, and stuttering.", whatItDoes: "Wipes outdated precompiled Vulkan/OpenGL/DirectX shaders downloaded from Steam CDN.", whenToUse: "When Steam games stutter after game patches or GPU driver updates.", steps: ["Open Steam → Settings → Downloads.", "Click 'Clear Cache' next to Clear Download Cache.", "Steam → Settings → Shader Pre-Caching → Turn OFF and back ON to regenerate fresh shaders."], url: "" },
  { id: 88, title: "Disable Discord & Browser Hardware Acceleration", category: "FPS & Gaming", type: "Setting", summary: "Prevents background apps from stealing GPU encoder cores and VRAM.", whatItDoes: "Forces Discord/browsers to use CPU software rendering instead of precious GPU compute.", whenToUse: "If your game frame rates drop while streaming to Discord or having videos on a 2nd monitor.", steps: ["Discord: User Settings → Advanced → Toggle 'Hardware Acceleration' to OFF.", "Chrome/Edge: Settings → System → Turn off 'Use graphics acceleration when available'."], url: "" },
  { id: 89, title: "Configure Optimal G-Sync + V-Sync Settings", category: "FPS & Gaming", type: "Setting", summary: "Achieves 100% tear-free gaming with zero input lag penalty.", whatItDoes: "Combines G-Sync adaptive module with driver-level V-Sync frame compensation below refresh rate.", whenToUse: "The universally agreed gold standard for variable refresh rate monitors.", steps: ["NVIDIA Control Panel: Set G-Sync to 'Enable for windowed and full screen mode'.", "Manage 3D Settings: Set Vertical Sync to 'ON' in NVIDIA Control Panel.", "Set Max Frame Rate to 3-4 FPS below monitor refresh (e.g. 141 FPS on 144Hz).", "In game settings: Turn V-Sync OFF."], url: "" },
  { id: 90, title: "Disable Windows GameDVR Broadcast via Registry", category: "Windows Debloat", type: "Setting", summary: "Completely terminates Windows background recording hooks.", whatItDoes: "Disables bcastdvr.exe and GameBarPresenceWriter.exe background processes entirely.", whenToUse: "If you want zero Windows background capture overhead.", steps: ["Open regedit → HKEY_CURRENT_USER\\System\\GameConfigStore.", "Set GameDVR_Enabled to 0.", "Go to HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\GameDVR.", "Create DWORD AllowGameDVR = 0.", "Restart PC."], url: "" },
  { id: 91, title: "Disable Windows 11 Copilot & AI Telemetry", category: "Windows Debloat", type: "Setting", summary: "Stops AI telemetry daemons from running in the background.", whatItDoes: "Disables Copilot taskbar hooks, web suggestions, and continuous screen polling.", whenToUse: "For Windows 11 users wanting a private, bloat-free system.", steps: ["Open regedit → HKEY_CURRENT_USER\\Software\\Policies\\Microsoft\\Windows\\WindowsCopilot.", "Create DWORD TurnOffWindowsCopilot = 1.", "Navigate to HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsCopilot.", "Create DWORD TurnOffWindowsCopilot = 1. Restart PC."], url: "" },
  { id: 92, title: "Disable Microsoft Edge Background Startup Boost", category: "Windows Debloat", type: "Setting", summary: "Stops Edge from pre-launching hidden background instances at boot.", whatItDoes: "Prevents msedge.exe from silently running in Task Manager when you never opened Edge.", whenToUse: "On all PCs where Edge is not your primary browser.", steps: ["Open Microsoft Edge → Settings → System and performance.", "Toggle OFF 'Startup boost'.", "Toggle OFF 'Continue running background extensions and apps when Microsoft Edge is closed'."], url: "" },
  { id: 93, title: "Disable Sticky Keys & FilterKeys Hotkey Popups", category: "Windows Debloat", type: "Setting", summary: "Prevents desktop-minimizing popup windows when pressing Shift 5 times in games.", whatItDoes: "Disables the accessibility shortcut triggers that tab you out during intense gameplay.", whenToUse: "Mandatory for all gamers who use the Shift key for sprinting or crouching.", steps: ["Settings → Accessibility → Keyboard.", "Click on Sticky Keys → Toggle OFF 'Keyboard shortcut for Sticky keys'.", "Click on Filter Keys → Toggle OFF 'Keyboard shortcut for Filter keys'."], url: "" },
  { id: 94, title: "Disable Windows Tips, Tricks and Suggestions", category: "Windows Debloat", type: "Setting", summary: "Stops annoying notification toasts and background push ad telemetry.", whatItDoes: "Disables Microsoft promotional notification background pushes.", whenToUse: "To silence non-essential OS prompts.", steps: ["Settings → System → Notifications.", "Scroll down to 'Additional settings'.", "Uncheck 'Show the Windows welcome experience', 'Suggest ways to get the most out of Windows', and 'Get tips and suggestions'."], url: "" },
  { id: 95, title: "Disable Windows Indexing Service on Gaming Drives", category: "SSD & Disk Cleaning", type: "Setting", summary: "Reduces continuous background SSD reads and writes.", whatItDoes: "Stops Windows Search from continuously indexing files inside game libraries.", whenToUse: "On secondary SSD/NVMe drives dedicated purely to game installations.", steps: ["Open File Explorer → This PC.", "Right-click your Game SSD (e.g. D: or E:) → Properties.", "Uncheck 'Allow files on this drive to have contents indexed in addition to file properties'.", "Apply changes to drive and subfolders."], url: "" },
  { id: 96, title: "Enable NTFS 8.3 Name Creation Disablement", category: "SSD & Disk Cleaning", type: "Setting", summary: "Speeds up file directory access and metadata operations by 10-20%.", whatItDoes: "Stops NTFS from creating legacy MS-DOS short 8-character aliases for every new file.", whenToUse: "On fast modern SSDs holding thousands of game files.", steps: ["Open CMD as Administrator.", "Run: fsutil 8dot3name set 1", "The change applies immediately across all NTFS volumes."], url: "" },
  { id: 97, title: "Compress Windows OS with CompactOS", category: "SSD & Disk Cleaning", type: "Setting", summary: "Reclaims 4GB - 12GB of C: drive space using zero CPU penalty compression.", whatItDoes: "Compresses core Windows system files using fast XPRESS8K transparent algorithms.", whenToUse: "For small 128GB or 256GB boot SSDs running low on storage.", steps: ["Open Command Prompt as Administrator.", "Type: compact.exe /compactos:always", "Windows will compress its operating binaries in 5-10 minutes."], url: "" },
  { id: 98, title: "Clean Deep Browser GPU & Code Caches", category: "SSD & Disk Cleaning", type: "Setting", summary: "Reclaims 3GB to 8GB of bloated hidden cache files.", whatItDoes: "Deletes orphaned GPU shader caches, V8 bytecode caches, and IndexedDB dumps.", whenToUse: "When browsers feel sluggish or C: drive space mysteriously vanishes.", steps: ["Press Win + R → type %LocalAppData%\\Google\\Chrome\\User Data\\Default.", "Delete contents of 'Service Worker\\CacheStorage', 'GPUCache', and 'Code Cache'.", "(Repeat for Microsoft\\Edge or BraveSoftware)."], url: "" },
  { id: 99, title: "Disable Windows Error Reporting (WER) Dump Buildup", category: "SSD & Disk Cleaning", type: "Setting", summary: "Prevents gigabytes of useless memory crash dump files from filling the drive.", whatItDoes: "Caps and disables automatic memory dump generation on user applications.", whenToUse: "To save SSD write wear and storage space.", steps: ["Press Win + R → type services.msc.", "Find 'Windows Error Reporting Service'.", "Right-click → Properties → Startup type: Disabled → Apply."], url: "" },
  { id: 100, title: "Disable IPv6 on Network Adapter (If ISP Unsupported)", category: "Network & Latency", type: "Setting", summary: "Eliminates 1-2 second DNS resolution delays caused by IPv6 fallbacks.", whatItDoes: "Stops Windows from attempting dual-stack IPv6 DNS queries when your ISP only routes IPv4.", whenToUse: "If web pages or game server connections hesitate for 2 seconds before connecting.", steps: ["Press Win + R → type ncpa.cpl → Press Enter.", "Right-click your active Ethernet/Wi-Fi adapter → Properties.", "Uncheck 'Internet Protocol Version 6 (TCP/IPv6)'.", "Click OK."], url: "" },
  { id: 101, title: "Disable Large Send Offload (LSO) on LAN Adapter", category: "Network & Latency", type: "Setting", summary: "Prevents packet bursts and buffer bloat latency spikes in online games.", whatItDoes: "Forces CPU to handle TCP packet segmentation rather than delegating large bursts to NIC firmware.", whenToUse: "When experiencing packet loss or rubber-banding in competitive games.", steps: ["Open Device Manager → Network Adapters.", "Right-click your Realtek/Intel Ethernet adapter → Properties → Advanced.", "Find 'Large Send Offload v2 (IPv4)' and 'Large Send Offload v2 (IPv6)' → Set both to Disabled.", "Click OK."], url: "" },
  { id: 102, title: "Disable Energy Efficient Ethernet & Green Ethernet", category: "Network & Latency", type: "Setting", summary: "Prevents network adapter micro-sleep states that cause ping spikes.", whatItDoes: "Stops LAN chip from cutting PHY power during low data transmission.", whenToUse: "Essential for stable, zero-jitter Ethernet gaming.", steps: ["Device Manager → Network Adapters → Properties → Advanced.", "Set 'Energy Efficient Ethernet' to Disabled.", "Set 'Green Ethernet' to Disabled.", "Set 'Gigabit Lite' to Disabled."], url: "" },
  { id: 103, title: "Optimize MTU and TCP Parameters with TCP Optimizer", category: "Network & Latency", type: "Tool", summary: "Calculates the mathematically optimal network buffer and MTU packet size.", whatItDoes: "Tunes TCP receive windows (RWIN), Congestion Provider (CTCP), and QoS packet scheduling.", whenToUse: "On all home PCs connected to high-speed broadband or fiber connections.", steps: ["Download TCP Optimizer by SpeedGuide.", "Run as Administrator.", "Select your network adapter and set slider to your internet download speed.", "Select 'Optimal' radio button at the bottom → Click 'Apply changes' → Restart."], url: "https://www.speedguide.net/downloads.php" },
  { id: 104, title: "Set Windows QoS Reserved Bandwidth to 0%", category: "Network & Latency", type: "Setting", summary: "Prevents Windows from reserving 20% of network throughput for background tasks.", whatItDoes: "Unlocks the full 100% connection pipeline for games and active applications.", whenToUse: "On all Windows Pro/Enterprise systems.", steps: ["Press Win + R → type gpedit.msc → Press Enter.", "Computer Configuration → Administrative Templates → Network → QoS Packet Scheduler.", "Double-click 'Limit reservable bandwidth'.", "Select 'Enabled' and set 'Bandwidth limit (%)' to 0 → Click Apply."], url: "" },
  { id: 105, title: "Flush and Rebuild ARP Routing Cache", category: "Network & Latency", type: "Setting", summary: "Fixes IP address conflict dropouts and stale router ARP bindings.", whatItDoes: "Clears outdated MAC-to-IP lookup tables stored in Windows network stack.", whenToUse: "When games disconnect with 'Connection Timed Out' or router restarts.", steps: ["Open CMD as Administrator.", "Run: netsh interface ip delete arpcache", "Run: ipconfig /renew", "Restart your PC."], url: "" },
  { id: 106, title: "Analyze Crash Dumps with BlueScreenView", category: "System Stability & Diagnostics", type: "Tool", summary: "Instantly identifies the exact driver or DLL file responsible for BSODs.", whatItDoes: "Parses C:\\Windows\\Minidump files and highlights crashing driver memory addresses in red.", whenToUse: "Immediately after your computer suffers a Blue Screen of Death.", steps: ["Download BlueScreenView by NirSoft.", "Run executable (no installation needed).", "Click the most recent crash entry at the top list.", "Inspect the pink-highlighted driver file (e.g. nvlddmkm.sys, ntoskrnl.exe)."], url: "https://www.nirsoft.net/utils/blue_screen_view.html" },
  { id: 107, title: "Stress Test CPU, GPU & Power Supply with OCCT", category: "System Stability & Diagnostics", type: "Tool", summary: "Industry gold standard for detecting hidden hardware errors and unstable overclocks.", whatItDoes: "Pushes mathematical AVX2/AVX-512 routines to test CPU, memory, 3D GPU, and VRAM stability.", whenToUse: "When buying new hardware, troubleshooting unexpected crashes, or testing undervolts.", steps: ["Download OCCT.", "Run the 'Memory' test for 30 minutes to verify RAM stability.", "Run the 'CPU' (Small Data Set, Extreme) test to verify cooler performance.", "Check the error counter at the bottom for any flagged hardware faults."], url: "https://www.ocbase.com" },
  { id: 108, title: "Benchmark Multi-Core Thermal Limits with Cinebench", category: "System Stability & Diagnostics", type: "Tool", summary: "Measures sustained CPU performance and flags thermal throttling.", whatItDoes: "Renders a photorealistic 3D scene using Cinema 4D engine to test maximum multi-threaded output.", whenToUse: "To verify if your CPU cooler is properly seated and applying adequate thermal paste.", steps: ["Download Cinebench R23 or Cinebench 2024.", "Open HWiNFO64 sensors in the background.", "Run the 'CPU (Multi Core)' 10-minute stability throttle test.", "Verify CPU temps stay below 90°C and check for clock speed drops."], url: "https://www.maxon.net/en/cinebench" },
  { id: 109, title: "Test GPU Artifacts & Thermal Stability with FurMark", category: "System Stability & Diagnostics", type: "Tool", summary: "Heavy OpenGL stress test to expose failing GPU VRMs, VRAM, and fans.", whatItDoes: "Renders intense fuzzy donut animations that push GPU power draw to 100% board limits.", whenToUse: "When buying a used graphics card or testing GPU fan curves.", steps: ["Download FurMark 2.", "Set resolution to your native monitor display.", "Run the stress test for 15 minutes while monitoring GPU core and hotspot temperature."], url: "https://geeks3d.com/furmark/" },
  { id: 110, title: "Analyze Crash Reports in Plain English with WhoCrashed", category: "System Stability & Diagnostics", type: "Tool", summary: "Translates complex memory crash codes into simple actionable explanations.", whatItDoes: "Reads kernel crash dumps and tells you in plain English what caused the system crash.", whenToUse: "If you don't know how to interpret raw hex dump files.", steps: ["Download & install WhoCrashed (Home Edition).", "Click 'Analyze' button at the top.", "Scroll down to the 'Conclusion' section for plain English repair advice."], url: "https://www.resplendence.com/whocrashed" },
  { id: 111, title: "Inspect Critical Errors in Windows Event Viewer", category: "System Stability & Diagnostics", type: "Setting", summary: "Reveals hidden hardware crashes, kernel power losses, and drive errors.", whatItDoes: "Logs all operating system hardware and software errors with exact event timestamps.", whenToUse: "When your PC suddenly restarts without showing a Blue Screen.", steps: ["Press Win + X → Event Viewer.", "Expand 'Custom Views' → Click 'Administrative Events'.", "Filter for 'Critical' (Event ID 41 indicates Kernel-Power failure or PSU shutoff).", "Inspect 'Error' entries timestamped right before the shutdown."], url: "" },
  { id: 112, title: "Update All Installed Software via Winget in 1 Click", category: "Utility Tools", type: "Setting", summary: "Updates all your installed programs, runtimes, and tools in a single command.", whatItDoes: "Queries the official Microsoft Windows Package Manager repository to download latest versions.", whenToUse: "Run monthly to patch security holes and bug fixes across all software.", steps: ["Open Command Prompt or Terminal as Administrator.", "Type: winget upgrade --all --include-unknown", "Press Enter and let Windows automatically download and install updates silently."], url: "" },
  { id: 113, title: "Benchmark 1% Low FPS & Frame Times with CapFrameX", category: "Utility Tools", type: "Tool", summary: "Captures true game smoothness, micro-stutters, and 0.1% / 1% low frame rates.", whatItDoes: "Hooks into PresentMon to record microsecond frame-time intervals during active gameplay.", whenToUse: "When comparing before-and-after optimization tweaks or benchmarking settings.", steps: ["Download and launch CapFrameX.", "Set hotkey (e.g. F11) to trigger recording for 30 seconds.", "Play your game, press F11, and view the detailed frame time variance graph."], url: "https://www.capframex.com" },
  { id: 114, title: "Style Clean Taskbars with TranslucentTB", category: "Utility Tools", type: "Tool", summary: "Makes Windows taskbar fully transparent with zero performance cost.", whatItDoes: "Lightweight utility that modifies Windows desktop window composition taskbar styling.", whenToUse: "For users wanting a modern, clean, borderless desktop look.", steps: ["Install TranslucentTB from Microsoft Store or GitHub.", "Right-click the system tray icon.", "Set Regular / Maximized Window styles to 'Clear' or 'Acrylic'."], url: "https://github.com/TranslucentTB/TranslucentTB" },
  { id: 115, title: "Lightweight Open Hardware Monitor", category: "Utility Tools", type: "Tool", summary: "Ultra-light hardware sensor monitor with minimal RAM and CPU footprint.", whatItDoes: "Displays temperatures, voltages, and fan speeds in a tiny tree-view without bloat.", whenToUse: "For low-spec systems where heavy monitoring suites consume too much memory.", steps: ["Download Open Hardware Monitor (portable zip).", "Run OpenHardwareMonitor.exe as Admin.", "View CPU, GPU, and SSD temperatures in real time."], url: "https://openhardwaremonitor.org" },
  { id: 116, title: "Bulk Rename Utility", category: "Utility Tools", type: "Tool", summary: "Batch rename thousands of files, game mods, and screenshots instantly.", whatItDoes: "Allows regex, prefix, suffix, numbering, and string replacement across huge file collections.", whenToUse: "When organizing game mods, texture packs, or media libraries.", steps: ["Download Bulk Rename Utility.", "Select folder containing files.", "Apply renaming criteria (e.g. Add Prefix, Numbering) → Click 'Rename'."], url: "https://www.bulkrenameutility.co.uk" },
  { id: 117, title: "7-Zip Built-In Memory & CPU Benchmark", category: "Utility Tools", type: "Tool", summary: "Tests RAM bandwidth and CPU integer performance in 5 seconds.", whatItDoes: "Measures MIPS (Million Instructions Per Second) compression/decompression speeds.", whenToUse: "Quick sanity check to verify if RAM overclocking or XMP profile improved memory bandwidth.", steps: ["Open 7-Zip File Manager.", "Click Tools → Benchmark.", "Observe Compression and Decompression MIPS ratings."], url: "https://www.7-zip.org" },
  { id: 118, title: "Enable Ultimate Windows Performance Power Plan via CMD", category: "CPU Tuning & Power", type: "Setting", summary: "Disables all core sleeping and micro-latencies on desktop hardware.", whatItDoes: "Unlocks the hidden OEM power scheme designed for workstation servers.", whenToUse: "For gaming desktop PCs plugged directly into wall outlets.", steps: ["Open Command Prompt as Administrator.", "Type: powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61", "Open Control Panel → Power Options → Select 'Ultimate Performance'."], url: "" },
  { id: 119, title: "Disable Windows Background Apps on Windows 10 & 11", category: "Windows Debloat", type: "Setting", summary: "Prevents UWP apps from running and consuming RAM while closed.", whatItDoes: "Shuts down background life cycles for Calculator, Maps, Paint, and weather tiles.", whenToUse: "To free up system RAM on all computers.", steps: ["Settings → Apps → Installed apps.", "Click three dots next to non-essential apps → Advanced options.", "Set 'Background apps permissions' to 'Never'."], url: "" },
  { id: 120, title: "Clean Steam Download & Shader Cache", category: "SSD & Disk Cleaning", type: "Setting", summary: "Fixes corrupt game updates and frees 5GB-20GB of disk clutter.", whatItDoes: "Purges incomplete download chunks from steamapps\\downloading directory.", whenToUse: "When Steam games refuse to update or report 'disk write error'.", steps: ["Open Steam → Settings → Downloads.", "Click 'Clear Download Cache'.", "Steam will restart and log you back in with fresh cache."], url: "" },
  { id: 121, title: "Check Hard Drive Health with CheckDisk (chkdsk)", category: "System Stability & Diagnostics", type: "Setting", summary: "Scans file system metadata and repairs bad sectors on storage drives.", whatItDoes: "Verifies file directory structure and recovers readable data from corrupted sectors.", whenToUse: "After unexpected power outages or file corruption messages.", steps: ["Open CMD as Administrator.", "Type: chkdsk C: /f /r", "Type Y when prompted to schedule on next reboot and restart PC."], url: "" },
  { id: 122, title: "Disable Remote Assistance & Remote Desktop if Unused", category: "Windows Debloat", type: "Setting", summary: "Closes background listening ports and reduces attack surface.", whatItDoes: "Stops Windows from listening on RDP port 3389 and running remote assistance daemons.", whenToUse: "For personal gaming and home computers.", steps: ["Press Win + R → type sysdm.cpl → Press Enter.", "Go to 'Remote' tab.", "Uncheck 'Allow Remote Assistance connections to this computer'.", "Select 'Don't allow remote connections to this computer'."], url: "" },
  { id: 123, title: "Set Ethernet Adapter Speed & Duplex to Full Duplex", category: "Network & Latency", type: "Setting", summary: "Locks network interface to maximum throughput without auto-negotiation lag.", whatItDoes: "Forces Gigabit (1.0 Gbps) or 2.5 Gbps Full Duplex mode on wired network cables.", whenToUse: "If Windows randomly downgrades network speed to 100 Mbps.", steps: ["Device Manager → Network Adapters → Properties → Advanced tab.", "Locate 'Speed & Duplex'.", "Change from 'Auto Negotiation' to '1.0 Gbps Full Duplex' (or 2.5 Gbps if supported).", "Click OK."], url: "" },
  { id: 124, title: "Purge Windows Component Store (WinSxS)", category: "SSD & Disk Cleaning", type: "Setting", summary: "Reclaims 5GB - 15GB by removing superseded Windows update components.", whatItDoes: "Permanently deletes old DLL versions replaced by newer cumulative updates.", whenToUse: "When C: drive is running low on space after several monthly update cycles.", steps: ["Open CMD as Administrator.", "Type: Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase", "Wait for operation to reach 100%."], url: "" },
  { id: 125, title: "Disable Mouse Polling Rate Bottleneck", category: "Audio & Input Latency", type: "Setting", summary: "Verifies true 1000Hz / 4000Hz / 8000Hz mouse polling stability.", whatItDoes: "Ensures USB port and CPU scheduler can handle ultra-high polling rate without frame drops.", whenToUse: "When using high-end gaming mice (e.g. Razer 8K, Logitech Superlight).", steps: ["Open an online Mouse Rate Checker or MouseTester software.", "Move mouse rapidly and verify frequency matches mouse specs (e.g. 1000Hz).", "If CPU spikes to 100% while moving mouse, reduce polling to 1000Hz or 2000Hz."], url: "" },
  { id: 126, title: "Disable Windows Spotlight on Lock Screen", category: "Windows Debloat", type: "Setting", summary: "Stops background bing image downloads and lock screen ad pushes.", whatItDoes: "Stops Windows from fetching daily 4K wallpaper files and promotional prompts.", whenToUse: "For faster boot-to-desktop times.", steps: ["Settings → Personalization → Lock screen.", "Set 'Personalize your lock screen' to Picture or Solid Color instead of Windows Spotlight."], url: "" },
  { id: 127, title: "Disable Start Menu Recommendations in Windows 11", category: "Windows Debloat", type: "Setting", summary: "Reclaims Start Menu real estate and stops cloud file indexing.", whatItDoes: "Hides recommended recent files and promoted app shortcuts in the Start menu.", whenToUse: "For a cleaner, instant Start Menu search experience.", steps: ["Settings → Personalization → Start.", "Turn OFF 'Show recently opened items in Start, Jump Lists, and File Explorer'.", "Turn OFF 'Show recommendations for tips, shortcuts, new apps, and more'."], url: "" },
  { id: 128, title: "Tune Virtual Memory Paging File on Multiple Drives", category: "RAM Optimization", type: "Setting", summary: "Distributes paging loads across your fastest NVMe drives.", whatItDoes: "Prevents virtual memory bottlenecking on a single disk during extreme memory loads.", whenToUse: "When your PC has 2 or more NVMe SSDs installed.", steps: ["Win + R → sysdm.cpl → Advanced → Performance Settings → Advanced → Virtual Memory.", "Uncheck automatic management.", "Assign 8192MB to 16384MB on your fastest secondary NVMe SSD.", "Set C: drive to a small 1024MB crash-dump paging file."], url: "" },
  { id: 129, title: "Check Battery Health on Gaming Laptops (powercfg)", category: "System Stability & Diagnostics", type: "Setting", summary: "Reveals exact battery wear percentage and capacity degradation.", whatItDoes: "Generates an official detailed HTML report of designed capacity vs full charge capacity.", whenToUse: "When laptop battery life drains quickly during casual use or light gaming.", steps: ["Open Command Prompt as Administrator.", "Type: powercfg /batteryreport /output C:\\battery-report.html", "Open C:\\battery-report.html in any browser and check 'Design Capacity' vs 'Full Charge Capacity'."], url: "" },
  { id: 130, title: "Disable Windows Game Bar Presence Writer", category: "FPS & Gaming", type: "Setting", summary: "Permanently stops the background executable GameBarPresenceWriter.exe.", whatItDoes: "Stops Windows from checking Xbox Live status for games not purchased from Microsoft Store.", whenToUse: "If GameBarPresenceWriter appears in Task Manager using CPU cycles.", steps: ["Open regedit → HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\GameDVR.", "Create or set DWORD AppCaptureEnabled = 0.", "Navigate to HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\WindowsRuntime\\ActivatableClassId\\Windows.Gaming.Preview.GamesEnumeration.Internal.GamePresence.", "Set Enabled to 0."], url: "" },
  { id: 131, title: "Disable Windows Delivery Optimization P2P Sharing", category: "Network & Latency", type: "Setting", summary: "Stops your PC from uploading Windows updates to stranger PCs on the web.", whatItDoes: "Prevents background uploads from saturating your home router upload bandwidth.", whenToUse: "Crucial for preventing random ping spikes in multiplayer games.", steps: ["Settings → Windows Update → Advanced options → Delivery Optimization.", "Toggle OFF 'Allow downloads from other PCs'."], url: "" },
  { id: 132, title: "Adjust In-Game DPI Scaling Override for Sharp Graphics", category: "FPS & Gaming", type: "Setting", summary: "Fixes blurry game rendering and incorrect mouse sensitivity scaling.", whatItDoes: "Passes raw monitor resolution directly to the game engine without Windows DPI stretching.", whenToUse: "When games look slightly fuzzy on 1440p or 4K monitors.", steps: ["Right-click game .exe → Properties → Compatibility.", "Click 'Change high DPI settings'.", "Check 'Override high DPI scaling behavior'.", "Set 'Scaling performed by:' to 'Application' → OK."], url: "" },
  { id: 133, title: "Clean Prefetch Folder Safely", category: "SSD & Disk Cleaning", type: "Setting", summary: "Cleans outdated application launch traces after major uninstalls.", whatItDoes: "Removes legacy .pf files from software you have already uninstalled from your PC.", whenToUse: "Once or twice a year after removing multiple heavy games/programs.", steps: ["Press Win + R → type prefetch → Click Continue if prompted for permission.", "Select old files corresponding to uninstalled software (or Ctrl+A) → Delete.", "Restart your PC to let Windows rebuild fresh prefetch tables for active apps."], url: "" },
  { id: 134, title: "Disable V-Sync in In-Game Menus When Using G-Sync/FreeSync", category: "FPS & Gaming", type: "Setting", summary: "Prevents double-buffering input delay when frame rates dip.", whatItDoes: "Ensures the GPU driver handles sync timing rather than game engine double-buffers.", whenToUse: "In all games when G-Sync / FreeSync is enabled in the driver control panel.", steps: ["Launch game → Options / Video Settings.", "Find 'V-Sync' or 'Vertical Sync' → Set to OFF.", "Set 'Display Mode' to Fullscreen or Borderless Fullscreen."], url: "" },
  { id: 135, title: "Backup Windows Registry before Deep System Tweaking", category: "System Stability & Diagnostics", type: "Setting", summary: "Guarantees full system recovery if any registry tweak causes issues.", whatItDoes: "Exports a complete copy of all system registry hives to an external backup file.", whenToUse: "Before editing any registry keys or running automated debloat utilities.", steps: ["Press Win + R → type regedit → Press Enter.", "Click 'Computer' at the top of the left tree.", "File → Export → Select 'All' export range.", "Save file as 'Registry_Backup.reg' to a safe location."], url: "" },
];

export default function PCOptimizationTools() {
  const [activeCategory, setActiveCategory] = useState("All");
  const [searchQuery, setSearchQuery] = useState("");
  const [expandedId, setExpandedId] = useState<number | null>(null);

  // Restore category from URL or sessionStorage on mount
  useEffect(() => {
    try {
      const urlParams = new URLSearchParams(window.location.search);
      const urlCat = urlParams.get("category");
      const storedCat = sessionStorage.getItem("mrfreqline_pc_opt_cat");
      const targetCat = urlCat || storedCat;
      if (targetCat && categories.some((c) => c.toLowerCase() === targetCat.toLowerCase())) {
        const found = categories.find((c) => c.toLowerCase() === targetCat.toLowerCase());
        if (found) setActiveCategory(found);
      }
    } catch {}
  }, []);

  // Sync category on back/forward browser slide gestures
  useEffect(() => {
    const onPopState = () => {
      try {
        const urlParams = new URLSearchParams(window.location.search);
        const urlCat = urlParams.get("category");
        if (urlCat) {
          const found = categories.find((c) => c.toLowerCase() === urlCat.toLowerCase());
          if (found) setActiveCategory(found);
        } else {
          const storedCat = sessionStorage.getItem("mrfreqline_pc_opt_cat");
          if (storedCat) {
            const found = categories.find((c) => c.toLowerCase() === storedCat.toLowerCase());
            if (found) setActiveCategory(found);
          } else {
            setActiveCategory("All");
          }
        }
      } catch {}
    };
    window.addEventListener("popstate", onPopState);
    return () => window.removeEventListener("popstate", onPopState);
  }, []);

  const handleCategoryChange = (cat: string) => {
    setActiveCategory(cat);
    try {
      sessionStorage.setItem("mrfreqline_pc_opt_cat", cat);
      const url = new URL(window.location.href);
      if (cat === "All") {
        url.searchParams.delete("category");
      } else {
        url.searchParams.set("category", cat);
      }
      window.history.replaceState(null, "", url.toString());
    } catch {}
  };

  const filteredData = optimizationData.filter((item) => {
    const itemCat = (item.category || "").trim().toUpperCase();
    const activeCat = activeCategory.trim().toUpperCase();
    const matchesCategory =
      activeCategory === "All" ||
      itemCat === activeCat ||
      (activeCat === "SYSTEM STABILITY & DIAGNOSTICS" && (itemCat === "SYSTEM STABILITY" || itemCat === "SYSTEM STABILITY & DIAGNOSTICS"));

    const query = searchQuery.trim().toLowerCase();
    if (!query) return matchesCategory;

    const stepsText = (item.steps || []).join(" ").toLowerCase();
    const matchesSearch =
      (item.title || "").toLowerCase().includes(query) ||
      (item.summary || "").toLowerCase().includes(query) ||
      (item.category || "").toLowerCase().includes(query) ||
      (item.whatItDoes || "").toLowerCase().includes(query) ||
      (item.whenToUse || "").toLowerCase().includes(query) ||
      stepsText.includes(query);

    return matchesCategory && matchesSearch;
  });

  const toggleExpand = (id: number) => { setExpandedId(expandedId === id ? null : id); };

  return (
    <>
      <Header />
      <main className="min-h-screen bg-[#08090b] px-6 pt-24 pb-16 text-white font-sans">
        <div className="mx-auto max-w-6xl">
          <div className="flex flex-col gap-4 border-b border-white/10 pb-6 md:flex-row md:items-center md:justify-between">
            <div>
              <h1 className="text-4xl font-black tracking-tight text-white">PC Optimization Guide & Tools</h1>
              <p className="mt-2 text-gray-400">{optimizationData.length} verified tweaks, settings, and utilities for maximum FPS, cleaner storage, and lower latency.</p>
            </div>
            <div className="rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-right">
              <span className="text-2xl font-bold text-[#00D2FF]">{filteredData.length}</span>
              <span className="ml-2 text-xs text-gray-400">Tips Found</span>
            </div>
          </div>

          <div className="mt-6 flex items-center gap-3 rounded-xl border border-yellow-500/30 bg-yellow-500/10 p-4 text-sm text-yellow-200">
            <span className="text-xl">⚠️</span>
            <div><strong>Safety Reminder:</strong> Always create a <u>System Restore Point</u> before applying registry edits, disabling services, or running debloat scripts.</div>
          </div>

          <div className="mt-8 space-y-4">
            <input type="text" placeholder="Search by keyword (e.g. FPS, RAM, SSD, Registry, NVIDIA)..." value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} className="w-full rounded-xl border border-white/10 bg-white/5 px-5 py-3 text-base sm:text-sm text-white placeholder-gray-500 focus:border-[#00D2FF] focus:outline-none focus:ring-1 focus:ring-[#00D2FF]" />
            <div className="flex flex-wrap gap-2.5 pt-2">
              {categories.map((cat) => (
                <button key={cat} onClick={() => handleCategoryChange(cat)} className={`rounded-full px-5 py-2 text-xs font-bold uppercase tracking-wider transition-all duration-200 ${activeCategory === cat ? "bg-[#00D2FF] text-black shadow-[0_0_15px_rgba(0,210,255,0.8)]" : "border border-white/10 bg-[#12161f] text-gray-200 hover:border-white/30 hover:bg-[#1a202c]"}`}>{cat}</button>
              ))}
            </div>
          </div>

          {/* Adsterra Responsive Banner */}
          <AdsterraBanner format="responsive" />

          <div className="mt-8 grid gap-4 md:grid-cols-2">
            {filteredData.map((item) => {
              const isExpanded = expandedId === item.id;
              return (
                <div key={item.id} className="flex flex-col justify-between rounded-2xl border border-white/10 bg-[#0d111a] p-5 transition hover:border-[#00D2FF]/40">
                  <div>
                    <div className="flex items-center justify-between text-xs">
                      <span className="rounded-full bg-[#00D2FF]/20 px-3 py-1 font-bold text-[#00D2FF]">{item.category}</span>
                      <span className="rounded-md bg-white/10 px-2 py-0.5 text-gray-400">{item.type}</span>
                    </div>
                    <h3 className="mt-3 text-lg font-bold text-white">#{item.id}. {item.title}</h3>
                    <p className="mt-2 text-sm text-gray-300">{item.summary}</p>
                    {isExpanded && (
                      <div className="mt-4 space-y-3 rounded-xl border border-white/10 bg-black/50 p-4 text-xs text-gray-300">
                        <div><strong className="text-[#00D2FF]">What It Does:</strong><p className="mt-1 text-gray-400">{item.whatItDoes}</p></div>
                        <div><strong className="text-[#00D2FF]">When To Apply:</strong><p className="mt-1 text-gray-400">{item.whenToUse}</p></div>
                        <div><strong className="text-[#00D2FF]">How To Do It (Steps):</strong><ol className="mt-1.5 list-inside list-decimal space-y-1 text-gray-300">{item.steps.map((step, idx) => (<li key={idx}>{step}</li>))}</ol></div>
                      </div>
                    )}
                    {item.type === "Tool" && item.url && (
                      <a href={item.url} target="_blank" rel="noopener noreferrer" className="mt-4 inline-block rounded-lg bg-[#00D2FF] px-4 py-2 text-xs font-bold text-black transition hover:opacity-90">⬇ Download / Official Site</a>
                    )}
                  </div>
                  <div className="mt-5 border-t border-white/10 pt-3 text-right">
                    <button onClick={() => toggleExpand(item.id)} className="text-xs font-semibold text-[#00D2FF] hover:underline">{isExpanded ? "Close Guide ▲" : "View Step-By-Step Guide ▼"}</button>
                  </div>
                </div>
              );
            })}
          </div>

          {filteredData.length === 0 && (<div className="mt-12 py-12 text-center text-gray-500">No matching tips found. Try searching for broader terms like "RAM", "GPU", or "Clean".</div>)}

          {/* Adsterra Native Banner */}
          <div className="mt-14 w-full">
            <AdsterraBanner format="native" />
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}